-- Slice 8: make resource semantics explicit and move teacher auxiliary records
-- to lifecycle-specific tables. The generic source remains until Slice 10.

ALTER TABLE center_material_library_items RENAME TO learning_resources;
ALTER TABLE classroom_materials RENAME TO class_resources;

ALTER TABLE users
    ADD COLUMN teacher_headline varchar(180),
    ADD COLUMN teacher_biography text,
    ADD COLUMN teacher_specializations varchar(700),
    ADD COLUMN teacher_teaching_languages varchar(300),
    ADD COLUMN teacher_years_of_experience integer,
    ADD COLUMN teacher_highest_qualification varchar(250),
    ADD COLUMN teacher_public_profile boolean NOT NULL DEFAULT false;

UPDATE users u
SET teacher_headline = p.headline,
    teacher_biography = p.biography,
    teacher_specializations = p.specializations,
    teacher_teaching_languages = p.teaching_languages,
    teacher_years_of_experience = p.years_of_experience,
    teacher_highest_qualification = p.highest_qualification,
    teacher_public_profile = COALESCE(p.public_profile, false)
FROM user_auxiliary_records p
WHERE p.record_type = 'teacher_professional_profiles'
  AND p.teacher_id = u.id;

CREATE TABLE teacher_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id bigint NOT NULL REFERENCES users(id),
    type varchar(40) NOT NULL,
    title varchar(250) NOT NULL,
    issuer varchar(250) NOT NULL,
    credential_number varchar(150),
    issued_date date,
    expiry_date date,
    document_url varchar(700),
    verification_status varchar(20) NOT NULL,
    verified_by_id bigint REFERENCES users(id),
    verified_at timestamp without time zone,
    verification_note varchar(700),
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE TABLE teacher_google_meet_connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id bigint NOT NULL UNIQUE REFERENCES users(id),
    google_subject varchar(255) NOT NULL,
    google_email varchar(255) NOT NULL,
    encrypted_refresh_token text NOT NULL,
    scopes varchar(500) NOT NULL,
    meet_connection_status varchar(30) NOT NULL,
    connected_at timestamp without time zone NOT NULL,
    last_used_at timestamp without time zone,
    revoked_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE TABLE teacher_course_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id bigint NOT NULL REFERENCES class_enrollments(id),
    class_section_id bigint NOT NULL REFERENCES class_sections(id),
    teacher_id bigint NOT NULL REFERENCES users(id),
    clarity_score integer NOT NULL,
    engagement_score integer NOT NULL,
    feedback_learner_support_score integer NOT NULL,
    feedback_timeliness_score integer NOT NULL,
    feedback_professionalism_score integer NOT NULL,
    pace varchar(20) NOT NULL,
    would_recommend boolean NOT NULL,
    strengths varchar(1500) NOT NULL,
    improvement_suggestions varchar(1500) NOT NULL,
    additional_comment varchar(1500),
    submitted_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    CONSTRAINT uk_teacher_feedback_enrollment_teacher UNIQUE (enrollment_id, teacher_id)
);

CREATE TABLE teacher_performance_evaluations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id bigint NOT NULL REFERENCES users(id),
    evaluator_id bigint NOT NULL REFERENCES users(id),
    period_start date NOT NULL,
    period_end date NOT NULL,
    lesson_delivery_score numeric(3,2) NOT NULL,
    evaluation_learner_support_score numeric(3,2) NOT NULL,
    grading_timeliness_score numeric(3,2) NOT NULL,
    evaluation_professionalism_score numeric(3,2) NOT NULL,
    overall_score numeric(3,2) NOT NULL,
    strengths varchar(1500),
    improvement_areas varchar(1500),
    action_plan varchar(1500),
    evaluation_status varchar(20) NOT NULL,
    published_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE TABLE learner_lesson_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    course_id bigint NOT NULL REFERENCES online_courses(id),
    lesson_id bigint NOT NULL REFERENCES online_lessons(id),
    content varchar(2000) NOT NULL,
    selected_text varchar(2000),
    transcript_start_seconds integer,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone
);

INSERT INTO teacher_credentials
SELECT id, teacher_id, type, title, issuer, credential_number, issued_date,
       expiry_date, document_url, verification_status, verified_by_id, verified_at,
       verification_note, created_at, updated_at
FROM user_auxiliary_records
WHERE record_type = 'teacher_credentials';

INSERT INTO teacher_google_meet_connections
SELECT id, teacher_id, google_subject, google_email, encrypted_refresh_token,
       scopes, meet_connection_status, connected_at, last_used_at, revoked_at,
       created_at, updated_at
FROM user_auxiliary_records
WHERE record_type = 'teacher_google_meet_connections';

INSERT INTO teacher_course_feedback
SELECT id, enrollment_id, class_section_id, teacher_id, clarity_score,
       engagement_score, feedback_learner_support_score, feedback_timeliness_score,
       feedback_professionalism_score, pace, would_recommend, strengths,
       improvement_suggestions, additional_comment, submitted_at, created_at, updated_at
FROM user_auxiliary_records
WHERE record_type = 'teacher_course_feedback';

INSERT INTO teacher_performance_evaluations
SELECT id, teacher_id, evaluator_id, period_start, period_end, lesson_delivery_score,
       evaluation_learner_support_score, grading_timeliness_score,
       evaluation_professionalism_score, overall_score, strengths, improvement_areas,
       action_plan, evaluation_status, published_at, created_at, updated_at
FROM user_auxiliary_records
WHERE record_type = 'teacher_performance_evaluations';

INSERT INTO learner_lesson_notes
SELECT id, user_id, course_id, lesson_id, content, selected_text,
       transcript_start_seconds, created_at, updated_at
FROM user_auxiliary_records
WHERE record_type = 'learner_lesson_notes';

SELECT setval(pg_get_serial_sequence('teacher_credentials', 'id'), COALESCE((SELECT max(id) FROM teacher_credentials), 1), EXISTS (SELECT 1 FROM teacher_credentials));
SELECT setval(pg_get_serial_sequence('teacher_google_meet_connections', 'id'), COALESCE((SELECT max(id) FROM teacher_google_meet_connections), 1), EXISTS (SELECT 1 FROM teacher_google_meet_connections));
SELECT setval(pg_get_serial_sequence('teacher_course_feedback', 'id'), COALESCE((SELECT max(id) FROM teacher_course_feedback), 1), EXISTS (SELECT 1 FROM teacher_course_feedback));
SELECT setval(pg_get_serial_sequence('teacher_performance_evaluations', 'id'), COALESCE((SELECT max(id) FROM teacher_performance_evaluations), 1), EXISTS (SELECT 1 FROM teacher_performance_evaluations));
SELECT setval(pg_get_serial_sequence('learner_lesson_notes', 'id'), COALESCE((SELECT max(id) FROM learner_lesson_notes), 1), EXISTS (SELECT 1 FROM learner_lesson_notes));

DO $$
DECLARE
    expected bigint;
    actual bigint;
BEGIN
    SELECT count(*) INTO expected FROM user_auxiliary_records
    WHERE record_type = 'teacher_professional_profiles';
    SELECT count(*) INTO actual FROM user_auxiliary_records p
    JOIN users u ON u.id = p.teacher_id
    WHERE p.record_type = 'teacher_professional_profiles'
      AND u.teacher_public_profile = COALESCE(p.public_profile, false);
    IF expected <> actual THEN
        RAISE EXCEPTION 'Slice 8 teacher profile reconciliation failed: expected %, got %', expected, actual;
    END IF;

    IF (SELECT count(*) FROM teacher_credentials) <>
       (SELECT count(*) FROM user_auxiliary_records WHERE record_type = 'teacher_credentials') OR
       (SELECT count(*) FROM teacher_google_meet_connections) <>
       (SELECT count(*) FROM user_auxiliary_records WHERE record_type = 'teacher_google_meet_connections') OR
       (SELECT count(*) FROM teacher_course_feedback) <>
       (SELECT count(*) FROM user_auxiliary_records WHERE record_type = 'teacher_course_feedback') OR
       (SELECT count(*) FROM teacher_performance_evaluations) <>
       (SELECT count(*) FROM user_auxiliary_records WHERE record_type = 'teacher_performance_evaluations') OR
       (SELECT count(*) FROM learner_lesson_notes) <>
       (SELECT count(*) FROM user_auxiliary_records WHERE record_type = 'learner_lesson_notes') THEN
        RAISE EXCEPTION 'Slice 8 auxiliary table reconciliation failed';
    END IF;
END $$;
