-- Slice 9: relational payment lines and independent tuition/proof lifecycles.
ALTER TABLE payment_orders RENAME COLUMN amount_vnd TO final_amount_vnd;

CREATE TABLE payment_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_order_id bigint NOT NULL REFERENCES payment_orders(id) ON DELETE CASCADE,
    item_type varchar(30) NOT NULL,
    online_course_id bigint REFERENCES online_courses(id),
    class_enrollment_id bigint REFERENCES class_enrollments(id),
    title_snapshot varchar(250) NOT NULL,
    unit_price_vnd bigint NOT NULL,
    discount_amount_vnd bigint NOT NULL DEFAULT 0,
    final_amount_vnd bigint NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    CONSTRAINT ck_payment_order_item_target CHECK (
        (item_type = 'ONLINE_COURSE' AND online_course_id IS NOT NULL AND class_enrollment_id IS NULL)
        OR
        (item_type = 'CLASS_ENROLLMENT' AND online_course_id IS NULL AND class_enrollment_id IS NOT NULL)
    ),
    CONSTRAINT ck_payment_order_item_amounts CHECK (
        quantity > 0 AND unit_price_vnd >= 0 AND discount_amount_vnd >= 0 AND final_amount_vnd >= 0
    )
);

CREATE INDEX idx_payment_order_items_order ON payment_order_items(payment_order_id);
CREATE INDEX idx_payment_order_items_online_course ON payment_order_items(online_course_id);
CREATE INDEX idx_payment_order_items_class_enrollment ON payment_order_items(class_enrollment_id);

WITH parsed AS (
    SELECT po.id AS payment_order_id,
           po.final_amount_vnd AS order_final,
           token::bigint AS online_course_id,
           ordinal AS item_order,
           count(*) OVER (PARTITION BY po.id) AS item_count
    FROM payment_orders po
    CROSS JOIN LATERAL unnest(string_to_array(po.course_ids_csv, ',')) WITH ORDINALITY AS ids(token, ordinal)
    WHERE NULLIF(BTRIM(po.course_ids_csv), '') IS NOT NULL
), priced AS (
    SELECT p.*, oc.title,
           GREATEST(0, round(COALESCE(oc.price, 0))::bigint) AS unit_price,
           SUM(GREATEST(0, round(COALESCE(oc.price, 0))::bigint)) OVER (PARTITION BY p.payment_order_id) AS unit_total
    FROM parsed p
    JOIN online_courses oc ON oc.id = p.online_course_id
), preliminary AS (
    SELECT priced.*,
           CASE WHEN unit_total > 0
                THEN floor(order_final::numeric * unit_price::numeric / unit_total)::bigint
                ELSE floor(order_final::numeric / item_count)::bigint
           END AS preliminary_final
    FROM priced
), allocated AS (
    SELECT preliminary.*,
           CASE WHEN item_order = item_count
                THEN order_final - (SUM(preliminary_final) OVER (PARTITION BY payment_order_id) - preliminary_final)
                ELSE preliminary_final
           END AS allocated_final
    FROM preliminary
)
INSERT INTO payment_order_items (
    payment_order_id, item_type, online_course_id, title_snapshot,
    unit_price_vnd, discount_amount_vnd, final_amount_vnd, quantity
)
SELECT payment_order_id, 'ONLINE_COURSE', online_course_id, title,
       unit_price, GREATEST(0, unit_price - allocated_final), allocated_final, 1
FROM allocated;

INSERT INTO payment_order_items (
    payment_order_id, item_type, class_enrollment_id, title_snapshot,
    unit_price_vnd, discount_amount_vnd, final_amount_vnd, quantity
)
SELECT po.id, 'CLASS_ENROLLMENT', po.enrollment_id,
       COALESCE(NULLIF(BTRIM(po.course_titles), ''), 'Học phí lớp học'),
       po.original_amount_vnd, GREATEST(0, po.original_amount_vnd - po.final_amount_vnd),
       po.final_amount_vnd, 1
FROM payment_orders po
WHERE po.enrollment_id IS NOT NULL;

CREATE TABLE tuition_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id bigint NOT NULL REFERENCES class_enrollments(id),
    amount numeric(12,2) NOT NULL,
    payment_kind varchar(30) NOT NULL,
    note text,
    recorded_by_id bigint REFERENCES users(id),
    created_at timestamp without time zone
);

CREATE TABLE tuition_payment_proofs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id bigint NOT NULL REFERENCES class_enrollments(id),
    amount numeric(12,2) NOT NULL,
    payment_kind varchar(30) NOT NULL,
    file_url varchar(500) NOT NULL,
    note text,
    status varchar(20) NOT NULL,
    review_note text,
    reviewed_by_id bigint REFERENCES users(id),
    reviewed_at timestamp without time zone,
    created_at timestamp without time zone
);

INSERT INTO tuition_payments
SELECT id, enrollment_id, amount, payment_kind, note, recorded_by_id, created_at
FROM classroom_financial_records
WHERE record_type = 'classroom_tuition_payments';

INSERT INTO tuition_payment_proofs
SELECT id, enrollment_id, amount, payment_kind, file_url, note, status,
       review_note, reviewed_by_id, reviewed_at, created_at
FROM classroom_financial_records
WHERE record_type = 'classroom_tuition_payment_proofs';

SELECT setval(pg_get_serial_sequence('tuition_payments', 'id'), COALESCE((SELECT max(id) FROM tuition_payments), 1), EXISTS (SELECT 1 FROM tuition_payments));
SELECT setval(pg_get_serial_sequence('tuition_payment_proofs', 'id'), COALESCE((SELECT max(id) FROM tuition_payment_proofs), 1), EXISTS (SELECT 1 FROM tuition_payment_proofs));

DO $$
DECLARE
    mismatch_count bigint;
BEGIN
    SELECT count(*) INTO mismatch_count
    FROM payment_orders po
    LEFT JOIN (
        SELECT payment_order_id, sum(final_amount_vnd * quantity) AS item_total
        FROM payment_order_items GROUP BY payment_order_id
    ) totals ON totals.payment_order_id = po.id
    WHERE COALESCE(totals.item_total, -1) <> po.final_amount_vnd;
    IF mismatch_count > 0 THEN
        RAISE EXCEPTION 'Slice 9 payment item reconciliation failed for % orders', mismatch_count;
    END IF;

    IF (SELECT count(*) FROM tuition_payments) <>
       (SELECT count(*) FROM classroom_financial_records WHERE record_type = 'classroom_tuition_payments') OR
       (SELECT count(*) FROM tuition_payment_proofs) <>
       (SELECT count(*) FROM classroom_financial_records WHERE record_type = 'classroom_tuition_payment_proofs') THEN
        RAISE EXCEPTION 'Slice 9 tuition reconciliation failed';
    END IF;
END $$;
