-- Split the legacy record-type tables back into domain-specific relational tables.
-- Flyway runs PostgreSQL migrations transactionally, so count mismatches roll back the whole change.

CREATE TABLE rubric_criteria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rubric_id bigint NOT NULL REFERENCES assessment_rubrics(id),
    name varchar(120) NOT NULL,
    weight integer NOT NULL,
    description varchar(500),
    band_descriptors text,
    display_order integer NOT NULL
);
INSERT INTO rubric_criteria (id, rubric_id, name, weight, description, band_descriptors, display_order)
SELECT id, rubric_id, name, weight, description, band_descriptors, display_order
FROM assessment_component_records WHERE record_type = 'rubric_criteria';

CREATE TABLE classroom_quiz_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id bigint NOT NULL REFERENCES classroom_quizzes(id) ON DELETE CASCADE,
    sort_order integer NOT NULL,
    prompt text NOT NULL,
    options_json text NOT NULL,
    correct_answer varchar(500) NOT NULL,
    explanation text
);
INSERT INTO classroom_quiz_questions (id, quiz_id, sort_order, prompt, options_json, correct_answer, explanation)
SELECT id, quiz_id, sort_order, prompt, options_json, correct_answer, explanation
FROM assessment_component_records WHERE record_type = 'classroom_quiz_questions';

CREATE TABLE course_lesson_flashcard_refs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id bigint NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    flashcard_set_id bigint NOT NULL REFERENCES flashcard_sets(id),
    display_order integer NOT NULL,
    CONSTRAINT uk_course_lesson_flashcard_ref UNIQUE (lesson_id, flashcard_set_id)
);
INSERT INTO course_lesson_flashcard_refs (id, lesson_id, flashcard_set_id, display_order)
SELECT id, lesson_id, flashcard_set_id, display_order
FROM assessment_component_records WHERE record_type = 'course_lesson_flashcard_refs';

CREATE TABLE teacher_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id bigint NOT NULL REFERENCES users(id),
    type varchar(40) NOT NULL,
    title varchar(250) NOT NULL,
    issuer varchar(250) NOT NULL,
    credential_number varchar(150),
    issued_date date,
    expiry_date date,
    document_url varchar(700),
    verification_status varchar(20) NOT NULL,
    verified_by_id bigint REFERENCES users(id),
    verified_at timestamp,
    verification_note varchar(700),
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
INSERT INTO teacher_credentials
SELECT id, teacher_id, type, title, issuer, credential_number, issued_date, expiry_date,
       document_url, verification_status, verified_by_id, verified_at, verification_note,
       created_at, updated_at
FROM user_auxiliary_records WHERE record_type = 'teacher_credentials';

CREATE TABLE teacher_course_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id bigint NOT NULL REFERENCES classroom_enrollments(id),
    classroom_offering_id bigint NOT NULL REFERENCES classroom_offerings(id),
    teacher_id bigint NOT NULL REFERENCES users(id),
    clarity_score integer NOT NULL,
    engagement_score integer NOT NULL,
    feedback_learner_support_score integer NOT NULL,
    feedback_timeliness_score integer NOT NULL,
    feedback_professionalism_score integer NOT NULL,
    pace varchar(20) NOT NULL,
    would_recommend boolean NOT NULL,
    strengths varchar(1500) NOT NULL,
    improvement_suggestions varchar(1500) NOT NULL,
    additional_comment varchar(1500),
    submitted_at timestamp NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_teacher_course_feedback_enrollment_teacher_v2 UNIQUE (enrollment_id, teacher_id)
);
INSERT INTO teacher_course_feedback
SELECT id, enrollment_id, classroom_offering_id, teacher_id, clarity_score, engagement_score,
       feedback_learner_support_score, feedback_timeliness_score, feedback_professionalism_score,
       pace, would_recommend, strengths, improvement_suggestions, additional_comment,
       submitted_at, created_at, updated_at
FROM user_auxiliary_records WHERE record_type = 'teacher_course_feedback';

CREATE TABLE teacher_performance_evaluations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id bigint NOT NULL REFERENCES users(id),
    evaluator_id bigint NOT NULL REFERENCES users(id),
    period_start date NOT NULL,
    period_end date NOT NULL,
    lesson_delivery_score numeric(3,2) NOT NULL,
    evaluation_learner_support_score numeric(3,2) NOT NULL,
    grading_timeliness_score numeric(3,2) NOT NULL,
    evaluation_professionalism_score numeric(3,2) NOT NULL,
    overall_score numeric(3,2) NOT NULL,
    strengths varchar(1500),
    improvement_areas varchar(1500),
    action_plan varchar(1500),
    evaluation_status varchar(20) NOT NULL,
    published_at timestamp,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT ck_teacher_evaluation_period CHECK (period_end >= period_start)
);
INSERT INTO teacher_performance_evaluations
SELECT id, teacher_id, evaluator_id, period_start, period_end, lesson_delivery_score,
       evaluation_learner_support_score, grading_timeliness_score,
       evaluation_professionalism_score, overall_score, strengths, improvement_areas,
       action_plan, evaluation_status, published_at, created_at, updated_at
FROM user_auxiliary_records WHERE record_type = 'teacher_performance_evaluations';

CREATE TABLE teacher_google_meet_connections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id bigint NOT NULL UNIQUE REFERENCES users(id),
    google_subject varchar(255) NOT NULL,
    google_email varchar(255) NOT NULL,
    encrypted_refresh_token text NOT NULL,
    scopes varchar(500) NOT NULL,
    meet_connection_status varchar(30) NOT NULL,
    connected_at timestamp NOT NULL,
    last_used_at timestamp,
    revoked_at timestamp,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL
);
INSERT INTO teacher_google_meet_connections
SELECT id, teacher_id, google_subject, google_email, encrypted_refresh_token, scopes,
       meet_connection_status, connected_at, last_used_at, revoked_at, created_at, updated_at
FROM user_auxiliary_records WHERE record_type = 'teacher_google_meet_connections';

CREATE TABLE teacher_professional_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id bigint NOT NULL UNIQUE REFERENCES users(id),
    headline varchar(180),
    biography text,
    specializations varchar(700),
    teaching_languages varchar(300),
    years_of_experience integer,
    highest_qualification varchar(250),
    public_profile boolean NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT ck_teacher_profile_experience CHECK (years_of_experience IS NULL OR years_of_experience >= 0)
);
INSERT INTO teacher_professional_profiles
SELECT id, teacher_id, headline, biography, specializations, teaching_languages,
       years_of_experience, highest_qualification, public_profile, created_at, updated_at
FROM user_auxiliary_records WHERE record_type = 'teacher_professional_profiles';

CREATE TABLE learner_lesson_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    course_id bigint NOT NULL REFERENCES online_courses(id),
    lesson_id bigint NOT NULL REFERENCES lessons(id),
    content varchar(2000) NOT NULL,
    selected_text varchar(2000),
    transcript_start_seconds integer,
    created_at timestamp NOT NULL,
    updated_at timestamp,
    CONSTRAINT ck_lesson_note_transcript_time CHECK (transcript_start_seconds IS NULL OR transcript_start_seconds >= 0)
);
INSERT INTO learner_lesson_notes
SELECT id, user_id, course_id, lesson_id, content, selected_text,
       transcript_start_seconds, created_at, updated_at
FROM user_auxiliary_records WHERE record_type = 'learner_lesson_notes';

CREATE TABLE learner_lesson_review_flags (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    course_id bigint NOT NULL REFERENCES online_courses(id),
    lesson_id bigint NOT NULL REFERENCES lessons(id),
    created_at timestamp NOT NULL,
    CONSTRAINT uk_learner_lesson_review_flag UNIQUE (user_id, lesson_id)
);
INSERT INTO learner_lesson_review_flags
SELECT id, user_id, course_id, lesson_id, created_at
FROM user_auxiliary_records WHERE record_type = 'learner_lesson_review_flags';

CREATE TABLE enrollment_request_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_request_id bigint NOT NULL REFERENCES course_enrollment_requests(id) ON DELETE CASCADE,
    from_status varchar(40),
    to_status varchar(40) NOT NULL,
    actor_id bigint REFERENCES users(id),
    transition_reason varchar(700),
    created_at timestamp NOT NULL
);
INSERT INTO enrollment_request_status_history
SELECT id, enrollment_request_id, from_status, to_status, actor_id, transition_reason, created_at
FROM classroom_operation_records WHERE record_type = 'course_enrollment_request_history';

CREATE TABLE classroom_proposal_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id bigint NOT NULL REFERENCES classroom_proposals(id) ON DELETE CASCADE,
    enrollment_request_id bigint NOT NULL REFERENCES course_enrollment_requests(id),
    classroom_enrollment_id bigint REFERENCES classroom_enrollments(id),
    created_at timestamp NOT NULL,
    CONSTRAINT uk_classroom_proposal_members_request_v2 UNIQUE (proposal_id, enrollment_request_id)
);
INSERT INTO classroom_proposal_members
SELECT id, proposal_id, enrollment_request_id, classroom_enrollment_id, created_at
FROM classroom_operation_records WHERE record_type = 'classroom_proposal_members';

CREATE TABLE classroom_attendance_disputes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id bigint NOT NULL REFERENCES classroom_attendance_records(id),
    student_id bigint NOT NULL REFERENCES users(id),
    dispute_reason text NOT NULL,
    dispute_status varchar(20) NOT NULL,
    review_note text,
    reviewed_by_id bigint REFERENCES users(id),
    reviewed_at timestamp,
    created_at timestamp,
    updated_at timestamp
);
INSERT INTO classroom_attendance_disputes
SELECT id, attendance_id, student_id, dispute_reason, dispute_status, review_note,
       reviewed_by_id, reviewed_at, created_at, updated_at
FROM classroom_operation_records WHERE record_type = 'classroom_attendance_disputes';

CREATE TABLE classroom_gradebook_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_offering_id bigint NOT NULL REFERENCES classroom_offerings(id),
    student_id bigint NOT NULL REFERENCES users(id),
    homework_score numeric(6,2),
    quiz_score numeric(6,2),
    attendance_percent numeric(5,2),
    participation_score numeric(6,2),
    final_result numeric(6,2),
    teacher_comment text,
    gradebook_status varchar(20) NOT NULL,
    updated_by_id bigint REFERENCES users(id),
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_classroom_gradebook_entry UNIQUE (classroom_offering_id, student_id),
    CONSTRAINT ck_gradebook_attendance_percent CHECK (attendance_percent IS NULL OR attendance_percent BETWEEN 0 AND 100)
);
INSERT INTO classroom_gradebook_entries
SELECT id, classroom_offering_id, student_id, homework_score, quiz_score,
       attendance_percent, participation_score, final_result, teacher_comment,
       gradebook_status, updated_by_id, created_at, updated_at
FROM classroom_operation_records WHERE record_type = 'classroom_gradebook_entries';

CREATE TABLE lark_meeting_participants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_session_id bigint NOT NULL REFERENCES classroom_sessions(id) ON DELETE CASCADE,
    participant_key varchar(255) NOT NULL,
    user_id bigint REFERENCES users(id),
    active boolean NOT NULL,
    joined_at timestamp,
    left_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_lark_meeting_participant UNIQUE (classroom_session_id, participant_key),
    CONSTRAINT ck_lark_participant_times CHECK (left_at IS NULL OR joined_at IS NULL OR left_at >= joined_at)
);
INSERT INTO lark_meeting_participants
SELECT id, classroom_session_id, participant_key, user_id, active,
       joined_at, left_at, created_at, updated_at
FROM classroom_operation_records WHERE record_type = 'lark_meeting_participants';

CREATE TABLE classroom_tuition_payment_proofs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id bigint NOT NULL REFERENCES classroom_enrollments(id),
    amount numeric(12,2) NOT NULL,
    payment_kind varchar(30) NOT NULL,
    file_url varchar(500) NOT NULL,
    note text,
    status varchar(20) NOT NULL,
    review_note text,
    reviewed_by_id bigint REFERENCES users(id),
    reviewed_at timestamp,
    created_at timestamp,
    CONSTRAINT ck_tuition_payment_proof_amount CHECK (amount > 0)
);
INSERT INTO classroom_tuition_payment_proofs
SELECT id, enrollment_id, amount, payment_kind, file_url, note, status,
       review_note, reviewed_by_id, reviewed_at, created_at
FROM classroom_financial_records WHERE record_type = 'classroom_tuition_payment_proofs';

CREATE TABLE classroom_tuition_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id bigint NOT NULL REFERENCES classroom_enrollments(id),
    amount numeric(12,2) NOT NULL,
    payment_kind varchar(30) NOT NULL,
    note text,
    recorded_by_id bigint REFERENCES users(id),
    created_at timestamp,
    CONSTRAINT ck_tuition_payment_amount CHECK (amount > 0)
);
INSERT INTO classroom_tuition_payments
SELECT id, enrollment_id, amount, payment_kind, note, recorded_by_id, created_at
FROM classroom_financial_records WHERE record_type = 'classroom_tuition_payments';

CREATE TABLE lesson_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL REFERENCES users(id),
    lesson_id bigint NOT NULL REFERENCES lessons(id),
    enrollment_id bigint NOT NULL REFERENCES package_enrollments(id),
    course_version_id bigint REFERENCES online_course_versions(id),
    lesson_key varchar(120),
    lesson_progress_status varchar(30) NOT NULL,
    progress_percent integer NOT NULL,
    completed_at timestamp,
    last_accessed_at timestamp,
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_lesson_progress_student_lesson_v2 UNIQUE (student_id, lesson_id),
    CONSTRAINT ck_lesson_progress_percent CHECK (progress_percent BETWEEN 0 AND 100)
);
INSERT INTO lesson_progress
SELECT id, student_id, lesson_id, enrollment_id, course_version_id, lesson_key,
       lesson_progress_status, progress_percent, completed_at, last_accessed_at,
       created_at, updated_at
FROM learner_progress_records WHERE record_type = 'lesson_progress';

CREATE TABLE vocabulary_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL REFERENCES users(id),
    course_id bigint NOT NULL REFERENCES online_courses(id),
    term_key varchar(220) NOT NULL,
    vocabulary_status varchar(30) NOT NULL,
    starred boolean NOT NULL,
    last_reviewed_at timestamp,
    review_count integer NOT NULL DEFAULT 0,
    correct_count integer NOT NULL DEFAULT 0,
    incorrect_count integer NOT NULL DEFAULT 0,
    last_result_correct boolean,
    created_at timestamp,
    updated_at timestamp,
    CONSTRAINT uk_vocabulary_progress_term UNIQUE (student_id, course_id, term_key),
    CONSTRAINT ck_vocabulary_progress_counts CHECK (review_count >= 0 AND correct_count >= 0 AND incorrect_count >= 0)
);
INSERT INTO vocabulary_progress
SELECT id, student_id, course_id, term_key, vocabulary_status, starred,
       last_reviewed_at, COALESCE(review_count, 0), COALESCE(correct_count, 0),
       COALESCE(incorrect_count, 0), last_result_correct, created_at, updated_at
FROM learner_progress_records WHERE record_type = 'vocabulary_progress';

DO $$
DECLARE
    source_count bigint;
    target_count bigint;
BEGIN
    SELECT count(*) INTO source_count FROM assessment_component_records;
    SELECT (SELECT count(*) FROM rubric_criteria)
         + (SELECT count(*) FROM classroom_quiz_questions)
         + (SELECT count(*) FROM course_lesson_flashcard_refs) INTO target_count;
    IF source_count <> target_count THEN
        RAISE EXCEPTION 'assessment component backfill mismatch: source %, target %', source_count, target_count;
    END IF;

    SELECT count(*) INTO source_count FROM user_auxiliary_records;
    SELECT (SELECT count(*) FROM teacher_credentials)
         + (SELECT count(*) FROM teacher_course_feedback)
         + (SELECT count(*) FROM teacher_performance_evaluations)
         + (SELECT count(*) FROM teacher_google_meet_connections)
         + (SELECT count(*) FROM teacher_professional_profiles)
         + (SELECT count(*) FROM learner_lesson_notes)
         + (SELECT count(*) FROM learner_lesson_review_flags) INTO target_count;
    IF source_count <> target_count THEN
        RAISE EXCEPTION 'user auxiliary backfill mismatch: source %, target %', source_count, target_count;
    END IF;

    SELECT count(*) INTO source_count FROM classroom_operation_records;
    SELECT (SELECT count(*) FROM enrollment_request_status_history)
         + (SELECT count(*) FROM classroom_proposal_members)
         + (SELECT count(*) FROM classroom_attendance_disputes)
         + (SELECT count(*) FROM classroom_gradebook_entries)
         + (SELECT count(*) FROM lark_meeting_participants) INTO target_count;
    IF source_count <> target_count THEN
        RAISE EXCEPTION 'classroom operation backfill mismatch: source %, target %', source_count, target_count;
    END IF;

    SELECT count(*) INTO source_count FROM classroom_financial_records;
    SELECT (SELECT count(*) FROM classroom_tuition_payment_proofs)
         + (SELECT count(*) FROM classroom_tuition_payments) INTO target_count;
    IF source_count <> target_count THEN
        RAISE EXCEPTION 'classroom financial backfill mismatch: source %, target %', source_count, target_count;
    END IF;

    SELECT count(*) INTO source_count FROM learner_progress_records;
    SELECT (SELECT count(*) FROM lesson_progress)
         + (SELECT count(*) FROM vocabulary_progress) INTO target_count;
    IF source_count <> target_count THEN
        RAISE EXCEPTION 'learner progress backfill mismatch: source %, target %', source_count, target_count;
    END IF;
END $$;

DO $$
DECLARE
    table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'rubric_criteria', 'classroom_quiz_questions', 'course_lesson_flashcard_refs',
        'teacher_credentials', 'teacher_course_feedback', 'teacher_performance_evaluations',
        'teacher_google_meet_connections', 'teacher_professional_profiles',
        'learner_lesson_notes', 'learner_lesson_review_flags',
        'enrollment_request_status_history', 'classroom_proposal_members',
        'classroom_attendance_disputes', 'classroom_gradebook_entries',
        'lark_meeting_participants', 'classroom_tuition_payment_proofs',
        'classroom_tuition_payments', 'lesson_progress', 'vocabulary_progress'
    ] LOOP
        EXECUTE format(
            'SELECT setval(pg_get_serial_sequence(%L, %L), COALESCE((SELECT max(id) FROM %I), 1), EXISTS (SELECT 1 FROM %I))',
            table_name, 'id', table_name, table_name
        );
    END LOOP;
END $$;

DROP TABLE assessment_component_records;
DROP TABLE user_auxiliary_records;
DROP TABLE classroom_operation_records;
DROP TABLE classroom_financial_records;
DROP TABLE learner_progress_records;
DROP TABLE IF EXISTS application_schema_migrations;
