-- Slice 3: Content Bank unification into content_bank_items (Revision 4.2).
-- KEEP legacy bank tables until Slice 10. Typed ID map is required (legacy IDs collide).
-- status vs active: BOTH kept — AssessmentBankItem already uses both as distinct concepts;
--   types with only one field derive the other during backfill.

CREATE TABLE IF NOT EXISTS content_bank_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_type varchar(30) NOT NULL,
    code varchar(120),
    title varchar(220) NOT NULL,
    description text,
    exam_category varchar(40),
    skill varchar(60),
    status varchar(30) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL DEFAULT 0,
    tags varchar(500),
    payload_jsonb jsonb NOT NULL DEFAULT '{}'::jsonb,
    rubric_bank_item_id bigint,
    created_by_id bigint REFERENCES users(id),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT content_bank_items_bank_type_check CHECK (
        bank_type IN ('ASSESSMENT', 'EXERCISE', 'RUBRIC', 'FLASHCARD', 'PLACEMENT_TEST')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_content_bank_items_code
    ON content_bank_items (code)
    WHERE code IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_content_bank_items_type ON content_bank_items (bank_type);
CREATE INDEX IF NOT EXISTS idx_content_bank_items_status ON content_bank_items (status);

CREATE TABLE IF NOT EXISTS content_bank_legacy_id_map (
    legacy_type varchar(30) NOT NULL,
    legacy_id bigint NOT NULL,
    content_bank_item_id bigint NOT NULL REFERENCES content_bank_items(id),
    PRIMARY KEY (legacy_type, legacy_id),
    CONSTRAINT content_bank_legacy_id_map_type_check CHECK (
        legacy_type IN ('ASSESSMENT', 'EXERCISE', 'RUBRIC', 'FLASHCARD', 'PLACEMENT_TEST')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_content_bank_legacy_map_target
    ON content_bank_legacy_id_map (content_bank_item_id);

-- ---------------------------------------------------------------------------
-- 1. RUBRIC first (criteria → payload.criteria)
-- ---------------------------------------------------------------------------
INSERT INTO content_bank_items (
    bank_type, code, title, description, exam_category, skill, status, active,
    display_order, tags, payload_jsonb, rubric_bank_item_id, created_by_id, created_at, updated_at
)
SELECT
    'RUBRIC',
    NULL,
    r.name,
    r.description,
    r.exam_type,
    r.skill::text,
    CASE WHEN r.active THEN 'PUBLISHED' ELSE 'ARCHIVED' END,
    r.active,
    0,
    NULL,
    jsonb_build_object(
        'taskType', r.task_type,
        'scoringScale', r.scoring_scale,
        'criteria', COALESCE((
            SELECT jsonb_agg(
                jsonb_build_object(
                    'name', c.name,
                    'weight', c.weight,
                    'description', c.description,
                    'bandDescriptors', c.band_descriptors,
                    'displayOrder', c.display_order
                ) ORDER BY c.display_order NULLS LAST, c.id
            )
            FROM assessment_component_records c
            WHERE c.record_type = 'rubric_criteria'
              AND c.rubric_id = r.id
        ), '[]'::jsonb)
    ),
    NULL,
    NULL,
    NOW(),
    NOW()
FROM assessment_rubrics r
ORDER BY r.id;

WITH ordered_legacy AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM assessment_rubrics
),
ordered_bank AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
    FROM content_bank_items WHERE bank_type = 'RUBRIC'
)
INSERT INTO content_bank_legacy_id_map (legacy_type, legacy_id, content_bank_item_id)
SELECT 'RUBRIC', l.id, b.id
FROM ordered_legacy l
JOIN ordered_bank b ON b.rn = l.rn;

-- ---------------------------------------------------------------------------
-- 2. ASSESSMENT (rubric_bank_item_id via map; body → payload)
-- ---------------------------------------------------------------------------
INSERT INTO content_bank_items (
    bank_type, code, title, description, exam_category, skill, status, active,
    display_order, tags, payload_jsonb, rubric_bank_item_id, created_by_id, created_at, updated_at
)
SELECT
    'ASSESSMENT',
    NULL,
    a.title,
    a.description,
    NULL,
    a.skill::text,
    COALESCE(NULLIF(a.status, ''), 'DRAFT'),
    a.active,
    COALESCE(a.display_order, 0),
    NULL,
    jsonb_strip_nulls(jsonb_build_object(
        'type', a.type,
        'assessmentType', a.assessment_type,
        'aiEvaluationMode', a.ai_evaluation_mode,
        'instructions', a.instructions,
        'objectiveAnswerKey', a.objective_answer_key,
        'uiConfigJson', a.ui_config_json,
        'contentJson', a.content_json,
        'passingScore', a.passing_score,
        'maxScore', a.max_score,
        'timeLimitMinutes', a.time_limit_minutes
    )),
    CASE WHEN a.rubric_id IS NULL THEN NULL ELSE (
        SELECT m.content_bank_item_id FROM content_bank_legacy_id_map m
        WHERE m.legacy_type = 'RUBRIC' AND m.legacy_id = a.rubric_id
    ) END,
    NULL,
    a.created_at,
    a.updated_at
FROM assessment_bank_items a
ORDER BY a.id;

WITH ordered_legacy AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM assessment_bank_items
),
ordered_bank AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
    FROM content_bank_items WHERE bank_type = 'ASSESSMENT'
)
INSERT INTO content_bank_legacy_id_map (legacy_type, legacy_id, content_bank_item_id)
SELECT 'ASSESSMENT', l.id, b.id
FROM ordered_legacy l
JOIN ordered_bank b ON b.rn = l.rn;

-- ---------------------------------------------------------------------------
-- 3. EXERCISE
-- ---------------------------------------------------------------------------
INSERT INTO content_bank_items (
    bank_type, code, title, description, exam_category, skill, status, active,
    display_order, tags, payload_jsonb, created_by_id, created_at, updated_at
)
SELECT
    'EXERCISE',
    NULL,
    e.title,
    NULL,
    NULL,
    e.skill,
    CASE WHEN e.active THEN 'PUBLISHED' ELSE 'ARCHIVED' END,
    e.active,
    0,
    e.tags,
    jsonb_strip_nulls(jsonb_build_object(
        'level', e.level,
        'exerciseType', e.exercise_type,
        'prompt', e.prompt,
        'answerKey', e.answer_key,
        'explanation', e.explanation
    )),
    e.created_by_id,
    e.created_at,
    e.updated_at
FROM exercise_bank_items e
ORDER BY e.id;

WITH ordered_legacy AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM exercise_bank_items
),
ordered_bank AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
    FROM content_bank_items WHERE bank_type = 'EXERCISE'
)
INSERT INTO content_bank_legacy_id_map (legacy_type, legacy_id, content_bank_item_id)
SELECT 'EXERCISE', l.id, b.id
FROM ordered_legacy l
JOIN ordered_bank b ON b.rn = l.rn;

-- ---------------------------------------------------------------------------
-- 4. FLASHCARD
-- ---------------------------------------------------------------------------
INSERT INTO content_bank_items (
    bank_type, code, title, description, exam_category, skill, status, active,
    display_order, tags, payload_jsonb, created_at, updated_at
)
SELECT
    'FLASHCARD',
    NULL,
    f.title,
    f.description,
    f.exam_category,
    f.skill,
    COALESCE(NULLIF(f.status, ''), 'DRAFT'),
    CASE WHEN COALESCE(f.status, 'DRAFT') IN ('ARCHIVED', 'INACTIVE') THEN false ELSE true END,
    COALESCE(f.display_order, 0),
    f.tags,
    jsonb_build_object(
        'cards', CASE
            WHEN f.cards_json IS NULL OR btrim(f.cards_json) = '' THEN '[]'::jsonb
            WHEN left(btrim(f.cards_json), 1) IN ('[', '{') THEN
                CASE WHEN f.cards_json::text ~ '^\s*[\[{]' THEN
                    COALESCE(f.cards_json::jsonb, '[]'::jsonb)
                ELSE jsonb_build_array(f.cards_json)
                END
            ELSE jsonb_build_array(f.cards_json)
        END
    ),
    f.created_at,
    f.updated_at
FROM flashcard_sets f
ORDER BY f.id;

WITH ordered_legacy AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM flashcard_sets
),
ordered_bank AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
    FROM content_bank_items WHERE bank_type = 'FLASHCARD'
)
INSERT INTO content_bank_legacy_id_map (legacy_type, legacy_id, content_bank_item_id)
SELECT 'FLASHCARD', l.id, b.id
FROM ordered_legacy l
JOIN ordered_bank b ON b.rn = l.rn;

-- ---------------------------------------------------------------------------
-- 5. PLACEMENT_TEST
-- ---------------------------------------------------------------------------
INSERT INTO content_bank_items (
    bank_type, code, title, description, exam_category, skill, status, active,
    display_order, tags, payload_jsonb, created_at, updated_at
)
SELECT
    'PLACEMENT_TEST',
    p.test_code,
    p.title,
    p.description,
    p.exam_type,
    NULL,
    CASE WHEN p.active THEN 'PUBLISHED' ELSE 'ARCHIVED' END,
    p.active,
    0,
    NULL,
    jsonb_strip_nulls(jsonb_build_object(
        'maxAttempts', p.max_attempts,
        'listeningConfig', COALESCE(p.listening_config_json::jsonb, '{}'::jsonb),
        'readingConfig', COALESCE(p.reading_config_json::jsonb, '{}'::jsonb),
        'writingConfig', COALESCE(p.writing_config_json::jsonb, '{}'::jsonb),
        'speakingConfig', COALESCE(p.speaking_config_json::jsonb, '{}'::jsonb),
        'toeicConfig', CASE
            WHEN p.toeic_config_json IS NULL OR btrim(p.toeic_config_json) = '' THEN NULL
            ELSE p.toeic_config_json::jsonb
        END
    )),
    p.updated_at,
    p.updated_at
FROM placement_test_definitions p
ORDER BY p.id;

WITH ordered_legacy AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM placement_test_definitions
),
ordered_bank AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
    FROM content_bank_items WHERE bank_type = 'PLACEMENT_TEST'
)
INSERT INTO content_bank_legacy_id_map (legacy_type, legacy_id, content_bank_item_id)
SELECT 'PLACEMENT_TEST', l.id, b.id
FROM ordered_legacy l
JOIN ordered_bank b ON b.rn = l.rn;

-- Self-FK for rubric_bank_item_id
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_content_bank_rubric_item') THEN
        ALTER TABLE content_bank_items
            ADD CONSTRAINT fk_content_bank_rubric_item
            FOREIGN KEY (rubric_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 6. Retarget dependent FKs (additive columns first where needed)
-- ---------------------------------------------------------------------------

-- course_assessments: add content_bank columns, backfill, swap
ALTER TABLE course_assessments
    ADD COLUMN IF NOT EXISTS assessment_content_bank_item_id bigint,
    ADD COLUMN IF NOT EXISTS rubric_content_bank_item_id bigint;

UPDATE course_assessments ca
SET assessment_content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE m.legacy_type = 'ASSESSMENT'
  AND m.legacy_id = ca.assessment_bank_item_id
  AND ca.assessment_bank_item_id IS NOT NULL;

UPDATE course_assessments ca
SET rubric_content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE m.legacy_type = 'RUBRIC'
  AND m.legacy_id = ca.rubric_id
  AND ca.rubric_id IS NOT NULL;

-- classroom_homework
ALTER TABLE classroom_homework
    ADD COLUMN IF NOT EXISTS assessment_content_bank_item_id bigint,
    ADD COLUMN IF NOT EXISTS rubric_content_bank_item_id bigint;

UPDATE classroom_homework h
SET assessment_content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE m.legacy_type = 'ASSESSMENT'
  AND m.legacy_id = h.assessment_bank_item_id
  AND h.assessment_bank_item_id IS NOT NULL;

UPDATE classroom_homework h
SET rubric_content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE m.legacy_type = 'RUBRIC'
  AND m.legacy_id = h.rubric_id
  AND h.rubric_id IS NOT NULL;

-- mock_test_attempts
ALTER TABLE mock_test_attempts
    ADD COLUMN IF NOT EXISTS assessment_content_bank_item_id bigint;

UPDATE mock_test_attempts mt
SET assessment_content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE m.legacy_type = 'ASSESSMENT'
  AND m.legacy_id = mt.assessment_bank_item_id
  AND mt.assessment_bank_item_id IS NOT NULL;

-- curriculum_resource_refs (typed columns)
ALTER TABLE curriculum_resource_refs
    ADD COLUMN IF NOT EXISTS content_bank_item_id bigint;

UPDATE curriculum_resource_refs r
SET content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE r.assessment_id IS NOT NULL
  AND m.legacy_type = 'ASSESSMENT'
  AND m.legacy_id = r.assessment_id;

UPDATE curriculum_resource_refs r
SET content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE r.exercise_id IS NOT NULL
  AND m.legacy_type = 'EXERCISE'
  AND m.legacy_id = r.exercise_id
  AND r.content_bank_item_id IS NULL;

UPDATE curriculum_resource_refs r
SET content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE r.flashcard_set_id IS NOT NULL
  AND m.legacy_type = 'FLASHCARD'
  AND m.legacy_id = r.flashcard_set_id
  AND r.content_bank_item_id IS NULL;

-- classroom_practice_attempt_history
ALTER TABLE classroom_practice_attempt_history
    ADD COLUMN IF NOT EXISTS exercise_content_bank_item_id bigint;

UPDATE classroom_practice_attempt_history p
SET exercise_content_bank_item_id = m.content_bank_item_id
FROM content_bank_legacy_id_map m
WHERE m.legacy_type = 'EXERCISE'
  AND m.legacy_id = p.exercise_id
  AND p.exercise_id IS NOT NULL;

-- placement_test_attempts
ALTER TABLE placement_test_attempts
    ADD COLUMN IF NOT EXISTS content_bank_item_id bigint;

UPDATE placement_test_attempts a
SET content_bank_item_id = cbi.id
FROM content_bank_items cbi
WHERE cbi.bank_type = 'PLACEMENT_TEST'
  AND cbi.code = a.test_code
  AND a.content_bank_item_id IS NULL;

-- Dedicated online_lesson_flashcard_refs (from STI)
CREATE TABLE IF NOT EXISTS online_lesson_flashcard_refs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    online_lesson_id bigint NOT NULL REFERENCES online_lessons(id),
    content_bank_item_id bigint NOT NULL REFERENCES content_bank_items(id),
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);

INSERT INTO online_lesson_flashcard_refs (
    id, online_lesson_id, content_bank_item_id, display_order, created_at, updated_at
) OVERRIDING SYSTEM VALUE
SELECT
    r.id,
    r.lesson_id,
    m.content_bank_item_id,
    COALESCE(r.display_order, 0),
    NOW(),
    NOW()
FROM assessment_component_records r
JOIN content_bank_legacy_id_map m
  ON m.legacy_type = 'FLASHCARD'
 AND m.legacy_id = r.flashcard_set_id
WHERE r.record_type = 'course_lesson_flashcard_refs'
  AND NOT EXISTS (SELECT 1 FROM online_lesson_flashcard_refs x WHERE x.id = r.id);

SELECT setval(
    pg_get_serial_sequence('online_lesson_flashcard_refs', 'id'),
    COALESCE((SELECT MAX(id) FROM online_lesson_flashcard_refs), 1),
    true
);

CREATE INDEX IF NOT EXISTS idx_olfr_lesson ON online_lesson_flashcard_refs (online_lesson_id);
CREATE INDEX IF NOT EXISTS idx_olfr_bank ON online_lesson_flashcard_refs (content_bank_item_id);

-- FKs on new columns
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ca_assessment_cbi') THEN
        ALTER TABLE course_assessments
            ADD CONSTRAINT fk_ca_assessment_cbi
            FOREIGN KEY (assessment_content_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ca_rubric_cbi') THEN
        ALTER TABLE course_assessments
            ADD CONSTRAINT fk_ca_rubric_cbi
            FOREIGN KEY (rubric_content_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hw_assessment_cbi') THEN
        ALTER TABLE classroom_homework
            ADD CONSTRAINT fk_hw_assessment_cbi
            FOREIGN KEY (assessment_content_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_hw_rubric_cbi') THEN
        ALTER TABLE classroom_homework
            ADD CONSTRAINT fk_hw_rubric_cbi
            FOREIGN KEY (rubric_content_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mta_assessment_cbi') THEN
        ALTER TABLE mock_test_attempts
            ADD CONSTRAINT fk_mta_assessment_cbi
            FOREIGN KEY (assessment_content_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_crr_content_bank') THEN
        ALTER TABLE curriculum_resource_refs
            ADD CONSTRAINT fk_crr_content_bank
            FOREIGN KEY (content_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cpah_exercise_cbi') THEN
        ALTER TABLE classroom_practice_attempt_history
            ADD CONSTRAINT fk_cpah_exercise_cbi
            FOREIGN KEY (exercise_content_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pta_content_bank') THEN
        ALTER TABLE placement_test_attempts
            ADD CONSTRAINT fk_pta_content_bank
            FOREIGN KEY (content_bank_item_id) REFERENCES content_bank_items(id);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 7. Reconciliation
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    legacy_a bigint; bank_a bigint;
    legacy_e bigint; bank_e bigint;
    legacy_r bigint; bank_r bigint;
    legacy_f bigint; bank_f bigint;
    legacy_p bigint; bank_p bigint;
    map_dup bigint;
    bad_rubric bigint;
    bad_flash bigint;
    bad_place bigint;
    orphan_map bigint;
BEGIN
    SELECT count(*) INTO legacy_a FROM assessment_bank_items;
    SELECT count(*) INTO bank_a FROM content_bank_items WHERE bank_type = 'ASSESSMENT';
    IF legacy_a <> bank_a THEN
        RAISE EXCEPTION 'Slice3 A failed: assessment legacy=% bank=%', legacy_a, bank_a;
    END IF;

    SELECT count(*) INTO legacy_e FROM exercise_bank_items;
    SELECT count(*) INTO bank_e FROM content_bank_items WHERE bank_type = 'EXERCISE';
    IF legacy_e <> bank_e THEN
        RAISE EXCEPTION 'Slice3 B failed: exercise legacy=% bank=%', legacy_e, bank_e;
    END IF;

    SELECT count(*) INTO legacy_r FROM assessment_rubrics;
    SELECT count(*) INTO bank_r FROM content_bank_items WHERE bank_type = 'RUBRIC';
    IF legacy_r <> bank_r THEN
        RAISE EXCEPTION 'Slice3 C failed: rubric legacy=% bank=%', legacy_r, bank_r;
    END IF;

    SELECT count(*) INTO legacy_f FROM flashcard_sets;
    SELECT count(*) INTO bank_f FROM content_bank_items WHERE bank_type = 'FLASHCARD';
    IF legacy_f <> bank_f THEN
        RAISE EXCEPTION 'Slice3 D failed: flashcard legacy=% bank=%', legacy_f, bank_f;
    END IF;

    SELECT count(*) INTO legacy_p FROM placement_test_definitions;
    SELECT count(*) INTO bank_p FROM content_bank_items WHERE bank_type = 'PLACEMENT_TEST';
    IF legacy_p <> bank_p THEN
        RAISE EXCEPTION 'Slice3 E failed: placement legacy=% bank=%', legacy_p, bank_p;
    END IF;

    IF (legacy_a + legacy_e + legacy_r + legacy_f + legacy_p)
       <> (SELECT count(*) FROM content_bank_items) THEN
        RAISE EXCEPTION 'Slice3 F failed: total mismatch';
    END IF;

    SELECT count(*) INTO map_dup FROM (
        SELECT legacy_type, legacy_id FROM content_bank_legacy_id_map
        GROUP BY 1,2 HAVING count(*) > 1
    ) d;
    IF map_dup <> 0 THEN
        RAISE EXCEPTION 'Slice3 G failed: duplicate typed keys';
    END IF;

    IF (SELECT count(*) FROM content_bank_legacy_id_map)
       <> (SELECT count(*) FROM content_bank_items) THEN
        RAISE EXCEPTION 'Slice3 H failed: map size != bank size';
    END IF;

    SELECT count(*) INTO bad_rubric
    FROM content_bank_items a
    JOIN content_bank_items r ON r.id = a.rubric_bank_item_id
    WHERE a.rubric_bank_item_id IS NOT NULL
      AND (a.bank_type <> 'ASSESSMENT' OR r.bank_type <> 'RUBRIC');
    IF bad_rubric <> 0 THEN
        RAISE EXCEPTION 'Slice3 I failed: bad rubric_bank_item_id refs=%', bad_rubric;
    END IF;

    SELECT count(*) INTO bad_flash
    FROM online_lesson_flashcard_refs r
    JOIN content_bank_items c ON c.id = r.content_bank_item_id
    WHERE c.bank_type <> 'FLASHCARD';
    IF bad_flash <> 0 THEN
        RAISE EXCEPTION 'Slice3 J failed: flashcard refs wrong type=%', bad_flash;
    END IF;

    SELECT count(*) INTO bad_place
    FROM placement_test_attempts a
    JOIN content_bank_items c ON c.id = a.content_bank_item_id
    WHERE a.content_bank_item_id IS NOT NULL AND c.bank_type <> 'PLACEMENT_TEST';
    IF bad_place <> 0 THEN
        RAISE EXCEPTION 'Slice3 K failed: placement attempts wrong type=%', bad_place;
    END IF;

    SELECT count(*) INTO orphan_map
    FROM content_bank_legacy_id_map m
    WHERE NOT EXISTS (SELECT 1 FROM content_bank_items c WHERE c.id = m.content_bank_item_id);
    IF orphan_map <> 0 THEN
        RAISE EXCEPTION 'Slice3 L failed: orphan map rows=%', orphan_map;
    END IF;
END $$;
