-- Slice 4: Discussion posts model (Revision 4.2).
-- KEEP legacy threads/replies tables until Slice 10.
-- Typed id map for THREAD/REPLY → post ids (independent sequences).

CREATE TABLE IF NOT EXISTS course_discussion_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint NOT NULL REFERENCES online_courses(id),
    lesson_id bigint REFERENCES online_lessons(id),
    parent_post_id bigint REFERENCES course_discussion_posts(id),
    author_id bigint NOT NULL REFERENCES users(id),
    post_type varchar(20) NOT NULL,
    title varchar(180),
    content text NOT NULL,
    accepted boolean NOT NULL DEFAULT false,
    status varchar(30) NOT NULL,
    reported_count integer NOT NULL DEFAULT 0,
    helpful_count integer NOT NULL DEFAULT 0,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT course_discussion_posts_type_check CHECK (post_type IN ('THREAD', 'REPLY')),
    CONSTRAINT course_discussion_posts_shape_check CHECK (
        (post_type = 'THREAD' AND parent_post_id IS NULL AND title IS NOT NULL)
        OR
        (post_type = 'REPLY' AND parent_post_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_cdp_course ON course_discussion_posts (course_id);
CREATE INDEX IF NOT EXISTS idx_cdp_lesson ON course_discussion_posts (lesson_id);
CREATE INDEX IF NOT EXISTS idx_cdp_parent ON course_discussion_posts (parent_post_id);
CREATE INDEX IF NOT EXISTS idx_cdp_author ON course_discussion_posts (author_id);

CREATE TABLE IF NOT EXISTS course_discussion_post_id_map (
    legacy_kind varchar(20) NOT NULL,
    legacy_id bigint NOT NULL,
    post_id bigint NOT NULL REFERENCES course_discussion_posts(id),
    PRIMARY KEY (legacy_kind, legacy_id),
    CONSTRAINT course_discussion_post_id_map_kind_check CHECK (legacy_kind IN ('THREAD', 'REPLY'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cdp_map_post ON course_discussion_post_id_map (post_id);

-- THREADS
INSERT INTO course_discussion_posts (
    post_type, course_id, lesson_id, parent_post_id, author_id,
    title, content, accepted, status, reported_count, helpful_count, created_at, updated_at
)
SELECT
    'THREAD',
    t.course_id,
    t.lesson_id,
    NULL,
    t.author_id,
    t.title,
    t.content,
    false,
    t.status,
    COALESCE(t.reported_count, 0),
    0,
    t.created_at,
    t.updated_at
FROM course_discussion_threads t
ORDER BY t.id;

WITH ordered_legacy AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM course_discussion_threads
),
ordered_posts AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
    FROM course_discussion_posts WHERE post_type = 'THREAD'
)
INSERT INTO course_discussion_post_id_map (legacy_kind, legacy_id, post_id)
SELECT 'THREAD', l.id, p.id
FROM ordered_legacy l
JOIN ordered_posts p ON p.rn = l.rn;

-- REPLIES
INSERT INTO course_discussion_posts (
    post_type, course_id, lesson_id, parent_post_id, author_id,
    title, content, accepted, status, reported_count, helpful_count, created_at, updated_at
)
SELECT
    'REPLY',
    t.course_id,
    t.lesson_id,
    m.post_id,
    r.author_id,
    NULL,
    r.content,
    COALESCE(r.accepted, false),
    r.status,
    COALESCE(r.reported_count, 0),
    COALESCE(r.helpful_count, 0),
    r.created_at,
    r.updated_at
FROM course_discussion_replies r
JOIN course_discussion_threads t ON t.id = r.thread_id
JOIN course_discussion_post_id_map m ON m.legacy_kind = 'THREAD' AND m.legacy_id = r.thread_id
ORDER BY r.id;

WITH ordered_legacy AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM course_discussion_replies
),
ordered_posts AS (
    SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
    FROM course_discussion_posts WHERE post_type = 'REPLY'
)
INSERT INTO course_discussion_post_id_map (legacy_kind, legacy_id, post_id)
SELECT 'REPLY', l.id, p.id
FROM ordered_legacy l
JOIN ordered_posts p ON p.rn = l.rn;

-- Reactions: additive post_id
ALTER TABLE course_discussion_reactions
    ADD COLUMN IF NOT EXISTS post_id bigint;

UPDATE course_discussion_reactions r
SET post_id = m.post_id
FROM course_discussion_post_id_map m
WHERE r.post_id IS NULL
  AND m.legacy_kind = 'THREAD'
  AND r.target_type::text IN ('THREAD', 'DISCUSSION_THREAD')
  AND m.legacy_id = r.target_id;

UPDATE course_discussion_reactions r
SET post_id = m.post_id
FROM course_discussion_post_id_map m
WHERE r.post_id IS NULL
  AND m.legacy_kind = 'REPLY'
  AND r.target_type::text IN ('REPLY', 'DISCUSSION_REPLY')
  AND m.legacy_id = r.target_id;

-- Also try enum names without prefix
UPDATE course_discussion_reactions r
SET post_id = m.post_id
FROM course_discussion_post_id_map m
WHERE r.post_id IS NULL
  AND (
    (m.legacy_kind = 'THREAD' AND upper(r.target_type::text) LIKE '%THREAD%')
    OR (m.legacy_kind = 'REPLY' AND upper(r.target_type::text) LIKE '%REPLY%')
  )
  AND m.legacy_id = r.target_id;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cdr_post') THEN
        ALTER TABLE course_discussion_reactions
            ADD CONSTRAINT fk_cdr_post FOREIGN KEY (post_id) REFERENCES course_discussion_posts(id);
    END IF;
END $$;

-- Reports: additive post_id
ALTER TABLE course_discussion_reports
    ADD COLUMN IF NOT EXISTS post_id bigint;

UPDATE course_discussion_reports r
SET post_id = m.post_id
FROM course_discussion_post_id_map m
WHERE r.post_id IS NULL
  AND (
    (m.legacy_kind = 'THREAD' AND upper(r.target_type::text) LIKE '%THREAD%')
    OR (m.legacy_kind = 'REPLY' AND upper(r.target_type::text) LIKE '%REPLY%')
  )
  AND m.legacy_id = r.target_id;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cdrep_post') THEN
        ALTER TABLE course_discussion_reports
            ADD CONSTRAINT fk_cdrep_post FOREIGN KEY (post_id) REFERENCES course_discussion_posts(id);
    END IF;
END $$;

-- Reconciliation
DO $$
DECLARE
    legacy_t bigint; posts_t bigint;
    legacy_r bigint; posts_r bigint;
    unmapped_react bigint;
    unmapped_rep bigint;
BEGIN
    SELECT count(*) INTO legacy_t FROM course_discussion_threads;
    SELECT count(*) INTO posts_t FROM course_discussion_posts WHERE post_type = 'THREAD';
    IF legacy_t <> posts_t THEN
        RAISE EXCEPTION 'Slice4 A failed: threads legacy=% posts=%', legacy_t, posts_t;
    END IF;

    SELECT count(*) INTO legacy_r FROM course_discussion_replies;
    SELECT count(*) INTO posts_r FROM course_discussion_posts WHERE post_type = 'REPLY';
    IF legacy_r <> posts_r THEN
        RAISE EXCEPTION 'Slice4 B failed: replies legacy=% posts=%', legacy_r, posts_r;
    END IF;

    SELECT count(*) INTO unmapped_react FROM course_discussion_reactions WHERE post_id IS NULL;
    IF unmapped_react <> 0 THEN
        RAISE EXCEPTION 'Slice4 C failed: reactions without post_id=%', unmapped_react;
    END IF;

    SELECT count(*) INTO unmapped_rep FROM course_discussion_reports WHERE post_id IS NULL;
    IF unmapped_rep <> 0 THEN
        RAISE EXCEPTION 'Slice4 D failed: reports without post_id=%', unmapped_rep;
    END IF;
END $$;
