-- Slice 5: Instructor-Led Course core (Revision 4.2).
-- Merge TrainingProgram + CurriculumProgram → instructor_led_courses.
-- CurriculumUnit → course_units; CurriculumSessionPlan → course_lessons;
-- CurriculumResourceRef → course_unit_content_refs.
-- KEEP all legacy tables until Slice 10. Typed id map required (TP/CP independent IDs).

-- ---------------------------------------------------------------------------
-- 1. Target tables
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS instructor_led_courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(120) NOT NULL,
    slug varchar(160) NOT NULL,
    title varchar(180) NOT NULL,
    short_description varchar(500),
    description text,
    exam_type varchar(30) NOT NULL DEFAULT 'IELTS',
    program_track varchar(60),
    level varchar(120),
    entry_level varchar(120),
    entry_placement_level varchar(30),
    focus_skills varchar(240),
    target_band numeric(3, 1),
    target_score integer,
    learning_outcomes text,
    teacher_guide text,
    base_tuition_fee_vnd numeric(12, 2) NOT NULL DEFAULT 0,
    sale_tuition_fee_vnd numeric(12, 2),
    duration_label varchar(80),
    thumbnail_url varchar(700),
    publication_status varchar(30) NOT NULL DEFAULT 'DRAFT',
    featured boolean NOT NULL DEFAULT false,
    display_order integer NOT NULL DEFAULT 0,
    created_by_id bigint REFERENCES users(id),
    submitted_at timestamp(6) without time zone,
    reviewed_by_id bigint REFERENCES users(id),
    reviewed_at timestamp(6) without time zone,
    review_note text,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT uk_instructor_led_courses_code UNIQUE (code),
    CONSTRAINT uk_instructor_led_courses_slug UNIQUE (slug)
);

CREATE INDEX IF NOT EXISTS idx_ilc_publication_status ON instructor_led_courses (publication_status);
CREATE INDEX IF NOT EXISTS idx_ilc_exam_type ON instructor_led_courses (exam_type);

CREATE TABLE IF NOT EXISTS instructor_led_course_id_map (
    legacy_kind varchar(30) NOT NULL,
    legacy_id bigint NOT NULL,
    instructor_led_course_id bigint NOT NULL REFERENCES instructor_led_courses(id),
    PRIMARY KEY (legacy_kind, legacy_id),
    CONSTRAINT instructor_led_course_id_map_kind_check CHECK (
        legacy_kind IN ('TRAINING_PROGRAM', 'CURRICULUM_PROGRAM')
    )
);

CREATE INDEX IF NOT EXISTS idx_ilc_id_map_target
    ON instructor_led_course_id_map (instructor_led_course_id);

CREATE TABLE IF NOT EXISTS course_units (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instructor_led_course_id bigint NOT NULL REFERENCES instructor_led_courses(id),
    code varchar(120),
    title varchar(180) NOT NULL,
    description varchar(700),
    learning_objectives text,
    sequence_number integer NOT NULL DEFAULT 0,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);

CREATE INDEX IF NOT EXISTS idx_course_units_ilc ON course_units (instructor_led_course_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_course_units_ilc_code
    ON course_units (instructor_led_course_id, code)
    WHERE code IS NOT NULL;

CREATE TABLE IF NOT EXISTS course_lessons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_unit_id bigint NOT NULL REFERENCES course_units(id),
    code varchar(120),
    title varchar(220) NOT NULL,
    description text,
    learning_objectives text,
    sequence_number integer NOT NULL DEFAULT 0,
    estimated_duration_minutes integer,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);

CREATE INDEX IF NOT EXISTS idx_course_lessons_unit ON course_lessons (course_unit_id);

CREATE TABLE IF NOT EXISTS course_unit_content_refs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_unit_id bigint NOT NULL REFERENCES course_units(id),
    content_type varchar(20) NOT NULL,
    sequence_number integer NOT NULL DEFAULT 0,
    note varchar(500),
    -- Slice 8 renames center_material_library_items → learning_resources; FK follows rename.
    learning_resource_id bigint REFERENCES center_material_library_items(id),
    content_bank_item_id bigint REFERENCES content_bank_items(id),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT course_unit_content_refs_type_check CHECK (
        content_type IN ('MATERIAL', 'EXERCISE', 'ASSESSMENT', 'FLASHCARD')
    ),
    CONSTRAINT ck_course_unit_content_ref_target CHECK (
        (content_type = 'MATERIAL'
            AND learning_resource_id IS NOT NULL
            AND content_bank_item_id IS NULL)
        OR (content_type IN ('EXERCISE', 'ASSESSMENT', 'FLASHCARD')
            AND content_bank_item_id IS NOT NULL
            AND learning_resource_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_cucr_unit ON course_unit_content_refs (course_unit_id);
CREATE INDEX IF NOT EXISTS idx_cucr_bank ON course_unit_content_refs (content_bank_item_id);
CREATE INDEX IF NOT EXISTS idx_cucr_resource ON course_unit_content_refs (learning_resource_id);

-- ---------------------------------------------------------------------------
-- 2. Guard: TP↔CP integrity before merge
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    v_tp_without_cp bigint;
    v_cp_without_tp bigint;
    v_offering_mismatch bigint;
BEGIN
    SELECT COUNT(*) INTO v_tp_without_cp
    FROM training_programs WHERE curriculum_program_id IS NULL;

    SELECT COUNT(*) INTO v_cp_without_tp
    FROM curriculum_programs cp
    WHERE NOT EXISTS (
        SELECT 1 FROM training_programs tp WHERE tp.curriculum_program_id = cp.id
    );

    SELECT COUNT(*) INTO v_offering_mismatch
    FROM classroom_offerings o
    JOIN training_programs t ON t.id = o.training_program_id
    WHERE o.curriculum_program_id IS DISTINCT FROM t.curriculum_program_id;

    IF v_tp_without_cp > 0 OR v_cp_without_tp > 0 OR v_offering_mismatch > 0 THEN
        RAISE EXCEPTION
            'Slice 5 ambiguous TP/CP mapping: tp_without_cp=%, cp_without_tp=%, offering_mismatch=%',
            v_tp_without_cp, v_cp_without_tp, v_offering_mismatch;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Backfill instructor_led_courses (one row per TP⋈CP; preserve TP.id)
-- ---------------------------------------------------------------------------
INSERT INTO instructor_led_courses (
    id, code, slug, title, short_description, description,
    exam_type, program_track, level, entry_level, entry_placement_level,
    focus_skills, target_band, target_score, learning_outcomes, teacher_guide,
    base_tuition_fee_vnd, sale_tuition_fee_vnd, duration_label, thumbnail_url,
    publication_status, featured, display_order,
    created_by_id, submitted_at, reviewed_by_id, reviewed_at, review_note,
    created_at, updated_at
)
SELECT
    tp.id,
    tp.code,
    tp.slug,
    COALESCE(NULLIF(TRIM(tp.title), ''), cp.title),
    tp.short_description,
    COALESCE(tp.description, cp.outcomes),
    COALESCE(NULLIF(TRIM(cp.exam_category), ''), 'IELTS'),
    cp.program_track,
    cp.entry_level,
    cp.entry_level,
    cp.entry_placement_level,
    cp.focus_skills,
    cp.target_band,
    cp.target_score,
    cp.outcomes,
    cp.teacher_guide,
    COALESCE(tp.price, 0),
    tp.sale_price,
    tp.duration,
    tp.thumbnail_url,
    CASE
        WHEN tp.status IN ('PUBLISHED', 'APPROVED') THEN 'PUBLISHED'
        WHEN tp.status IN ('ARCHIVED', 'INACTIVE') THEN 'ARCHIVED'
        ELSE COALESCE(NULLIF(TRIM(tp.status), ''), 'DRAFT')
    END,
    COALESCE(tp.featured, false),
    COALESCE(tp.display_order, cp.display_order, 0),
    cp.submitted_by_id,
    cp.submitted_at,
    cp.reviewed_by_id,
    cp.reviewed_at,
    cp.review_note,
    COALESCE(tp.created_at, cp.created_at, NOW()),
    COALESCE(tp.updated_at, cp.updated_at, NOW())
FROM training_programs tp
JOIN curriculum_programs cp ON cp.id = tp.curriculum_program_id
ORDER BY tp.id;

SELECT setval(
    pg_get_serial_sequence('instructor_led_courses', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM instructor_led_courses), 1)
);

INSERT INTO instructor_led_course_id_map (legacy_kind, legacy_id, instructor_led_course_id)
SELECT 'TRAINING_PROGRAM', tp.id, tp.id
FROM training_programs tp;

INSERT INTO instructor_led_course_id_map (legacy_kind, legacy_id, instructor_led_course_id)
SELECT 'CURRICULUM_PROGRAM', tp.curriculum_program_id, tp.id
FROM training_programs tp;

-- ---------------------------------------------------------------------------
-- 4. Backfill course_units (preserve curriculum_units.id)
-- ---------------------------------------------------------------------------
INSERT INTO course_units (
    id, instructor_led_course_id, code, title, description,
    learning_objectives, sequence_number, created_at, updated_at
)
SELECT
    u.id,
    m.instructor_led_course_id,
    'CU-' || u.id::text,
    u.title,
    u.description,
    NULL,
    COALESCE(u.display_order, 0),
    u.created_at,
    u.updated_at
FROM curriculum_units u
JOIN instructor_led_course_id_map m
  ON m.legacy_kind = 'CURRICULUM_PROGRAM' AND m.legacy_id = u.program_id
ORDER BY u.id;

SELECT setval(
    pg_get_serial_sequence('course_units', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM course_units), 1)
);

-- ---------------------------------------------------------------------------
-- 5. Backfill course_lessons (preserve curriculum_session_plans.id)
-- ---------------------------------------------------------------------------
INSERT INTO course_lessons (
    id, course_unit_id, code, title, description, learning_objectives,
    sequence_number, estimated_duration_minutes, created_at, updated_at
)
SELECT
    sp.id,
    sp.unit_id,
    'CL-' || sp.id::text,
    sp.title,
    sp.description,
    sp.learning_objectives,
    COALESCE(sp.session_number, sp.display_order, 0),
    NULL,
    sp.created_at,
    sp.updated_at
FROM curriculum_session_plans sp
ORDER BY sp.id;

SELECT setval(
    pg_get_serial_sequence('course_lessons', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM course_lessons), 1)
);

-- ---------------------------------------------------------------------------
-- 6. Backfill course_unit_content_refs (preserve curriculum_resource_refs.id)
-- ---------------------------------------------------------------------------
INSERT INTO course_unit_content_refs (
    id, course_unit_id, content_type, sequence_number, note,
    learning_resource_id, content_bank_item_id, created_at, updated_at
)
SELECT
    r.id,
    r.unit_id,
    r.resource_type,
    COALESCE(r.display_order, 0),
    r.note,
    CASE WHEN r.resource_type = 'MATERIAL' THEN r.material_id ELSE NULL END,
    CASE
        WHEN r.resource_type IN ('EXERCISE', 'ASSESSMENT', 'FLASHCARD')
            THEN r.content_bank_item_id
        ELSE NULL
    END,
    NOW(),
    NOW()
FROM curriculum_resource_refs r
ORDER BY r.id;

SELECT setval(
    pg_get_serial_sequence('course_unit_content_refs', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM course_unit_content_refs), 1)
);

-- ---------------------------------------------------------------------------
-- 7. Additive dependent FKs (Slice 6 will rename offerings/sessions)
-- ---------------------------------------------------------------------------
ALTER TABLE classroom_offerings
    ADD COLUMN IF NOT EXISTS instructor_led_course_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_classroom_offerings_ilc'
    ) THEN
        ALTER TABLE classroom_offerings
            ADD CONSTRAINT fk_classroom_offerings_ilc
            FOREIGN KEY (instructor_led_course_id) REFERENCES instructor_led_courses(id);
    END IF;
END $$;

UPDATE classroom_offerings o
SET instructor_led_course_id = m.instructor_led_course_id
FROM instructor_led_course_id_map m
WHERE m.legacy_kind = 'TRAINING_PROGRAM'
  AND m.legacy_id = o.training_program_id
  AND o.training_program_id IS NOT NULL
  AND o.instructor_led_course_id IS NULL;

UPDATE classroom_offerings o
SET instructor_led_course_id = m.instructor_led_course_id
FROM instructor_led_course_id_map m
WHERE m.legacy_kind = 'CURRICULUM_PROGRAM'
  AND m.legacy_id = o.curriculum_program_id
  AND o.curriculum_program_id IS NOT NULL
  AND o.instructor_led_course_id IS NULL;

ALTER TABLE classroom_sessions
    ADD COLUMN IF NOT EXISTS course_lesson_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_classroom_sessions_course_lesson'
    ) THEN
        ALTER TABLE classroom_sessions
            ADD CONSTRAINT fk_classroom_sessions_course_lesson
            FOREIGN KEY (course_lesson_id) REFERENCES course_lessons(id);
    END IF;
END $$;

UPDATE classroom_sessions s
SET course_lesson_id = s.curriculum_session_plan_id
WHERE s.curriculum_session_plan_id IS NOT NULL
  AND s.course_lesson_id IS NULL
  AND EXISTS (SELECT 1 FROM course_lessons cl WHERE cl.id = s.curriculum_session_plan_id);

ALTER TABLE classroom_homework
    ADD COLUMN IF NOT EXISTS course_unit_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_classroom_homework_course_unit'
    ) THEN
        ALTER TABLE classroom_homework
            ADD CONSTRAINT fk_classroom_homework_course_unit
            FOREIGN KEY (course_unit_id) REFERENCES course_units(id);
    END IF;
END $$;

UPDATE classroom_homework h
SET course_unit_id = h.curriculum_unit_id
WHERE h.curriculum_unit_id IS NOT NULL
  AND h.course_unit_id IS NULL
  AND EXISTS (SELECT 1 FROM course_units cu WHERE cu.id = h.curriculum_unit_id);

ALTER TABLE classroom_materials
    ADD COLUMN IF NOT EXISTS course_unit_id bigint;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_classroom_materials_course_unit'
    ) THEN
        ALTER TABLE classroom_materials
            ADD CONSTRAINT fk_classroom_materials_course_unit
            FOREIGN KEY (course_unit_id) REFERENCES course_units(id);
    END IF;
END $$;

UPDATE classroom_materials m
SET course_unit_id = m.curriculum_unit_id
WHERE m.curriculum_unit_id IS NOT NULL
  AND m.course_unit_id IS NULL
  AND EXISTS (SELECT 1 FROM course_units cu WHERE cu.id = m.curriculum_unit_id);

-- ---------------------------------------------------------------------------
-- 8. Reconciliation (fail migration on mismatch)
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    v_tp bigint;
    v_cp bigint;
    v_ilc bigint;
    v_map bigint;
    v_units_src bigint;
    v_units_dst bigint;
    v_lessons_src bigint;
    v_lessons_dst bigint;
    v_refs_src bigint;
    v_refs_dst bigint;
    v_orphan_unit bigint;
    v_orphan_lesson bigint;
    v_orphan_ref bigint;
    v_bad_bank_type bigint;
    v_offering_missing bigint;
BEGIN
    SELECT COUNT(*) INTO v_tp FROM training_programs;
    SELECT COUNT(*) INTO v_cp FROM curriculum_programs;
    SELECT COUNT(*) INTO v_ilc FROM instructor_led_courses;
    SELECT COUNT(*) INTO v_map FROM instructor_led_course_id_map;
    SELECT COUNT(*) INTO v_units_src FROM curriculum_units;
    SELECT COUNT(*) INTO v_units_dst FROM course_units;
    SELECT COUNT(*) INTO v_lessons_src FROM curriculum_session_plans;
    SELECT COUNT(*) INTO v_lessons_dst FROM course_lessons;
    SELECT COUNT(*) INTO v_refs_src FROM curriculum_resource_refs;
    SELECT COUNT(*) INTO v_refs_dst FROM course_unit_content_refs;

    IF v_tp <> v_cp OR v_ilc <> v_tp OR v_map <> (v_tp + v_cp) THEN
        RAISE EXCEPTION
            'Slice 5 ILC count mismatch: tp=%, cp=%, ilc=%, map=%',
            v_tp, v_cp, v_ilc, v_map;
    END IF;
    IF v_units_src <> v_units_dst THEN
        RAISE EXCEPTION 'Slice 5 unit count mismatch: src=%, dst=%', v_units_src, v_units_dst;
    END IF;
    IF v_lessons_src <> v_lessons_dst THEN
        RAISE EXCEPTION 'Slice 5 lesson count mismatch: src=%, dst=%', v_lessons_src, v_lessons_dst;
    END IF;
    IF v_refs_src <> v_refs_dst THEN
        RAISE EXCEPTION 'Slice 5 content-ref count mismatch: src=%, dst=%', v_refs_src, v_refs_dst;
    END IF;

    SELECT COUNT(*) INTO v_orphan_unit
    FROM course_units u
    LEFT JOIN instructor_led_courses c ON c.id = u.instructor_led_course_id
    WHERE c.id IS NULL;

    SELECT COUNT(*) INTO v_orphan_lesson
    FROM course_lessons l
    LEFT JOIN course_units u ON u.id = l.course_unit_id
    WHERE u.id IS NULL;

    SELECT COUNT(*) INTO v_orphan_ref
    FROM course_unit_content_refs r
    LEFT JOIN course_units u ON u.id = r.course_unit_id
    WHERE u.id IS NULL;

    IF v_orphan_unit > 0 OR v_orphan_lesson > 0 OR v_orphan_ref > 0 THEN
        RAISE EXCEPTION
            'Slice 5 orphan FKs: units=%, lessons=%, refs=%',
            v_orphan_unit, v_orphan_lesson, v_orphan_ref;
    END IF;

    SELECT COUNT(*) INTO v_bad_bank_type
    FROM course_unit_content_refs r
    JOIN content_bank_items b ON b.id = r.content_bank_item_id
    WHERE (r.content_type = 'EXERCISE' AND b.bank_type <> 'EXERCISE')
       OR (r.content_type = 'ASSESSMENT' AND b.bank_type <> 'ASSESSMENT')
       OR (r.content_type = 'FLASHCARD' AND b.bank_type <> 'FLASHCARD');

    IF v_bad_bank_type > 0 THEN
        RAISE EXCEPTION 'Slice 5 content_bank_item bank_type mismatch: %', v_bad_bank_type;
    END IF;

    SELECT COUNT(*) INTO v_offering_missing
    FROM classroom_offerings
    WHERE training_program_id IS NOT NULL
      AND instructor_led_course_id IS NULL;

    IF v_offering_missing > 0 THEN
        RAISE EXCEPTION
            'Slice 5 offerings missing instructor_led_course_id: %',
            v_offering_missing;
    END IF;
END $$;
