/** TABLE_MATRIX rows for every known EnglishLab table/mode. */

export function buildTableMatrix(counts = {}) {
  const row = (table, entity, domain, mode, importance, target, actual, deps, naturalKey, cleanup, validation, notes) => ({
    table_name: table,
    entity,
    domain,
    mode,
    importance,
    target_rows: target,
    actual_rows: actual ?? "",
    date_from: mode === "MASTER" ? "2026-06-01" : "",
    date_to: mode === "MASTER" ? "2026-10-31" : "",
    source: mode === "MASTER" ? "master-dataset.json" : mode === "PROTECTED" ? "protected seeder" : mode === "PRESERVED" ? "existing DB" : "system/flyway",
    dependencies: deps,
    natural_key: naturalKey,
    cleanup_marker: mode === "MASTER" ? "MASTER_OPS / gv.|hs.|nv.|ilc-* / legacy demo-*|DEMO_*" : "",
    semantic_validation: validation,
    notes,
  });

  return [
    row("roles", "Role", "auth", "SYSTEM", "high", "6", "", "", "code", "", "enum codes", "Flyway + Role seed"),
    row("users", "User", "auth", "MASTER", "high", "340-360", counts.users_master, "roles", "email", "gv.|hs.|nv.|ql.|cm.|ad.@englishlab.vn exact", "vietnamese_name", "Preserved Gmail excluded from ownership"),
    row("user_roles", "User.roles", "auth", "MASTER", "high", "340-360", counts.users_master, "users,roles", "user_id+role_code", "via users", "role consistency", "Join table"),
    row("auth_tokens", "AuthToken", "auth", "KEEP_EMPTY", "low", "0", 0, "users", "token", "", "", "Runtime only"),
    row("course_categories", "CourseCategory", "catalog", "SYSTEM", "medium", "4-6", 5, "", "code", "", "", "IELTS/TOEIC/Communication/Foundation/Business"),
    row("online_courses", "OnlineCourse", "catalog", "MASTER", "high", "10-15", counts.online_courses_total_target, "course_categories", "slug", "ilc-* + legacy demo-*", "no placeholder titles", "E2+Vocab PROTECTED + master extras"),
    row("online_course_versions", "OnlineCourseVersion", "catalog", "DERIVED", "high", "per course", "", "online_courses", "course+version", "", "", "Snapshot for published courses"),
    row("online_course_modules", "OnlineCourseModule", "catalog", "MASTER", "medium", "sparse", "", "online_courses", "course+order", "ilc-*", "", "Full modules only for learning-flow courses"),
    row("online_lessons", "OnlineLesson", "catalog", "MASTER", "medium", "sparse", "", "modules", "stableLessonKey", "ilc-*", "", "Avoid regenerating protected lesson media"),
    row("online_course_enrollments", "OnlineCourseEnrollment", "learning", "MASTER", "high", "40-80", counts.online_enrollments, "users,online_courses", "student+course", "MASTER_OPS", "progress 0-100", "Do not reset preserved learner enrollments"),
    row("lesson_progress", "LessonProgress", "learning", "MASTER", "high", "200-400", counts.online_enrollments ? counts.online_enrollments * 3 : "", "enrollments,lessons", "enrollment+lesson", "MASTER_OPS", "no invalid progress", "Preserved progress KEEP AS-IS"),
    row("learner_lesson_notes", "LearnerLessonNote", "learning", "MASTER", "low", "10-30", counts.lessonNotes, "lessons,users", "id", "MASTER_OPS", "", "Optional notes"),
    row("course_discussion_posts", "CourseDiscussionPost", "learning", "MASTER", "medium", "20-50", counts.discussions, "courses,users", "id", "MASTER_OPS", "no lorem", "Discussion + reactions if present"),
    row("course_discussion_replies", "CourseDiscussionReply", "learning", "MASTER", "medium", "40-120", counts.discussionReplies, "posts,users", "naturalKey", "MASTER_OPS", "", "Nested in JSON discussionReplies"),
    row("course_discussion_reactions", "CourseDiscussionReaction", "learning", "MASTER", "medium", "50-200", counts.discussionReactions, "posts,users", "post+user", "MASTER_OPS", "unique per user", ""),
    row("course_discussion_reports", "CourseDiscussionReport", "learning", "MASTER", "medium", "8-15", counts.discussionReports, "posts,users", "naturalKey", "MASTER_OPS", "review chronology", ""),
    row("instructor_led_courses", "InstructorLedCourse", "catalog", "MASTER", "high", "4-8", counts.instructor_led_courses, "categories", "code", "ILC_* + legacy DEMO_*", "", "Center programs"),
    row("course_units", "CourseUnit", "catalog", "MASTER", "medium", "per ILC", "", "instructor_led_courses", "course+seq", "ILC_* + legacy DEMO_*", "", "Syllabus skeleton"),
    row("course_lessons", "CourseLesson", "catalog", "MASTER", "medium", "per unit", "", "course_units", "unit+seq", "ILC_* + legacy DEMO_*", "", "Outline only for most programs"),
    row("course_unit_content_refs", "CourseUnitContentRef", "catalog", "MASTER", "low", "0-20", "", "units,content_bank", "unit+ref", "MASTER_OPS", "", "Optional links"),
    row("rooms", "Room", "classroom", "MASTER", "medium", "10", counts.rooms, "", "code/name", "ILC_R* / Phòng *", "", "Hai Bà Trưng campus"),
    row("class_sections", "ClassSection", "classroom", "MASTER", "high", "50", counts.classrooms, "ILC,rooms,teachers", "code", "ilc-* + legacy demo-class-*", "no room/teacher clash", "Jun-Oct intakes"),
    row("class_schedules", "ClassSchedule", "classroom", "MASTER", "high", "1500-1800", counts.sessions, "class_sections", "class|date|time", "ilc-* + legacy demo-class-*", "temporal status", "Sessions"),
    row("class_enrollments", "ClassEnrollment", "classroom", "MASTER", "high", "100-180", counts.class_enrollments, "users,class_sections", "student+section", "MASTER_OPS", "capacity", "Story enrollments"),
    row("classroom_attendance_records", "ClassroomAttendance", "classroom", "MASTER", "high", "500-900", counts.attendance, "schedules,users", "session+student", "MASTER_OPS", "no future PRESENT", "Natural PRESENT-heavy"),
    row("classroom_homework", "ClassroomHomework", "classroom", "MASTER", "high", "30-60", counts.homework, "class_sections", "naturalKey", "MASTER_OPS", "publish before due", ""),
    row("classroom_homework_submissions", "ClassroomHomeworkSubmission", "classroom", "MASTER", "high", "120-250", counts.homework_submissions, "homework,users", "homework+student", "MASTER_OPS", "grade after submit", ""),
    row("classroom_operation_records", "ClassroomGradebookEntry", "classroom", "MASTER", "high", "120-250", counts.gradebook, "class_sections,users", "section+student", "MASTER_OPS", "score consistency", "Gradebook rows (record_type)"),
    row("class_resources", "ClassroomMaterial", "classroom", "MASTER", "medium", "30-60", counts.materials, "class_sections", "naturalKey", "MASTER_OPS", "", ""),
    row("classroom_announcements", "ClassroomAnnouncement", "classroom", "MASTER", "medium", "15-30", counts.announcements, "class_sections", "id", "MASTER_OPS", "", ""),
    row("classroom_proposals", "ClassroomProposal", "ops", "MASTER", "medium", "15-30", counts.proposals, "ILC,users", "naturalKey", "MASTER_OPS", "review chronology", ""),
    row("classroom_proposal_schedule_items", "ClassroomProposalScheduleItem", "ops", "MASTER", "low", "per proposal", "", "proposals", "proposal+slot", "MASTER_OPS", "", ""),
    row("course_registration_requests", "CourseRegistrationRequest", "ops", "MASTER", "medium", "15-40", counts.registrations, "users,ILC", "naturalKey", "MASTER_OPS", "", ""),
    row("classroom_change_requests", "ClassroomChangeRequest", "ops", "MASTER", "low", "5-15", counts.changeRequests, "users,classes", "id", "MASTER_OPS", "", "Do not overwrite preserved teacher history"),
    row("tuition_payments", "ClassroomTuitionPayment", "ops", "MASTER", "medium", "40-80", counts.tuitionPayments, "enrollments", "id", "MASTER_OPS", "amount vs tuition", ""),
    row("tuition_payment_proofs", "ClassroomTuitionPaymentProof", "ops", "MASTER", "low", "10-30", counts.tuitionProofs, "tuition_payments", "id", "MASTER_OPS", "proof review consistency", ""),
    row("learning_resources", "CenterMaterialLibraryItem", "content", "MASTER", "medium", "20-40", counts.centerLibrary, "", "title", "MASTER_OPS", "", "Center library"),
    row("course_list_items", "CourseListItem", "commerce", "MASTER", "medium", "20-40", counts.courseListItems, "users,online_courses", "learner+course+type", "MASTER_OPS", "", "Cart + wishlist"),
    row("content_bank_items", "ContentBankItem+", "content", "PROTECTED", "high", "existing", "", "", "title/type", "", "do not regenerate placement/mock/media", "Placement/Mock/Flashcard/Exercise shared table"),
    row("payment_orders", "PaymentOrder", "commerce", "MASTER", "high", "50-100", counts.payments, "users", "orderCode", "MASTER_OPS / 9xxxxx", "amount chronology", ""),
    row("payment_order_items", "PaymentOrderItem", "commerce", "MASTER", "high", "50-100", counts.payments, "payment_orders", "order+item", "MASTER_OPS", "", ""),
    row("discount_codes", "DiscountCode", "commerce", "MASTER", "medium", "3-8", 3, "", "code", "ILC_* + legacy DEMO_*", "", ""),
    row("support_tickets", "SupportTicket", "support", "MASTER", "medium", "20-40", counts.support_tickets, "users", "naturalKey", "MASTER_OPS", "closed after created", ""),
    row("support_ticket_messages", "SupportTicketMessage", "support", "MASTER", "medium", "40-80", counts.ticketMessages, "tickets", "id", "MASTER_OPS", "", ""),
    row("app_notifications", "AppNotification", "comms", "MASTER", "medium", "80-150", counts.notifications, "users", "naturalKey", "MASTER_OPS", "", ""),
    row("admin_broadcasts", "AdminBroadcast", "comms", "MASTER", "low", "3-8", counts.broadcasts, "users", "id", "MASTER_OPS", "schedule vs status", ""),
    row("teacher_credentials", "TeacherCredential", "teacher", "MASTER", "medium", "10-20", counts.teacherCredentials, "users", "id", "MASTER_OPS", "", "Do not overwrite preserved teacher credentials"),
    row("teacher_performance_evaluations", "TeacherPerformanceEvaluation", "teacher", "MASTER", "medium", "15-30", counts.evaluations, "users", "naturalKey", "MASTER_OPS", "period <= REF", ""),
    row("teacher_course_feedback", "TeacherCourseFeedback", "teacher", "MASTER", "low", "10-20", counts.teacherFeedback, "users,courses", "id", "MASTER_OPS", "", ""),
    row("teacher_google_meet_connections", "TeacherGoogleMeetConnection", "teacher", "PRESERVED", "high", "existing", "", "users", "teacher_id", "", "never overwrite", "alien1062004 Google Meet"),
    row("learning_paths", "LearningPath", "catalog", "SYSTEM", "medium", "existing", "", "", "code", "", "", "Flyway V22 defaults"),
    row("placement_test_attempts", "PlacementTestAttempt", "assessment", "PRESERVED", "high", "existing", "", "users", "student+test", "", "KEEP", "Protected assessment flow"),
    row("mock_test_attempts", "MockTestAttempt", "assessment", "KEEP_EMPTY", "medium", "0-n", "", "content_bank,users", "id", "", "", "Optional; do not fabricate protected keys"),
    row("assessment_submissions", "AssessmentSubmission", "assessment", "PRESERVED", "high", "existing", "", "assessments,users", "id", "", "KEEP showcase", "Do not reset preserved AI evaluations"),
    row("course_assessments", "CourseAssessment", "assessment", "PROTECTED", "high", "existing", "", "courses", "id", "", "", "Linked to protected course content"),
    row("classroom_practice_attempt_history", "ClassroomPracticeAttemptHistory", "classroom", "MASTER", "low", "10-40", counts.practiceAttempts, "classes,users", "id", "MASTER_OPS", "", ""),
    row("classroom_attendance_disputes", "ClassroomAttendance (dispute fields)", "classroom", "MASTER", "low", "8-15", counts.attendanceDisputes, "attendance", "attendanceNaturalKey", "MASTER_OPS", "", "Separate JSON array patches ABSENT rows"),
    row("master_flashcard_sets", "ContentBankItem (FLASHCARD)", "content", "MASTER", "medium", "5-10", counts.flashcardSets, "users", "code", "ilc-fc-* + legacy demo-fc-*", "", "MASTER sets only; protected bank untouched"),
    row("system_audit_logs", "AuditLog", "system", "KEEP_EMPTY", "low", "0", 0, "", "id", "", "", "Runtime"),
    row("flyway_schema_history", "Flyway", "system", "SYSTEM", "high", "n/a", "", "", "version", "", "", "Never delete"),
    row("online_lesson_flashcard_refs", "CourseLessonFlashcardRef", "catalog", "PROTECTED", "medium", "existing", "", "lessons,flashcards", "lesson+set", "", "", "Reuse protected flashcards"),
  ];
}
