DO $$
DECLARE
    domain_table TEXT;
    source_table TEXT;
    source_column RECORD;
    target_column TEXT;
    primary_key_name TEXT;
BEGIN
    FOREACH domain_table IN ARRAY ARRAY[
        'user_auxiliary_records',
        'assessment_component_records',
        'classroom_operation_records',
        'classroom_financial_records',
        'learner_progress_records'
    ]
    LOOP
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I ('
            || 'id BIGINT GENERATED BY DEFAULT AS IDENTITY, '
            || 'record_type VARCHAR(100) NOT NULL)',
            domain_table
        );
        EXECUTE format(
            'ALTER TABLE %I ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY',
            domain_table
        );
        EXECUTE format(
            'ALTER TABLE %I ADD COLUMN IF NOT EXISTS record_type VARCHAR(100)',
            domain_table
        );
    END LOOP;

    FOR domain_table, source_table IN
        SELECT * FROM (VALUES
            ('user_auxiliary_records', 'teacher_professional_profiles'),
            ('user_auxiliary_records', 'teacher_google_meet_connections'),
            ('user_auxiliary_records', 'learner_lesson_notes'),
            ('user_auxiliary_records', 'learner_lesson_review_flags'),
            ('user_auxiliary_records', 'teacher_credentials'),
            ('user_auxiliary_records', 'teacher_performance_evaluations'),
            ('user_auxiliary_records', 'teacher_course_feedback'),
            ('assessment_component_records', 'rubric_criteria'),
            ('assessment_component_records', 'classroom_quiz_questions'),
            ('assessment_component_records', 'course_lesson_flashcard_refs'),
            ('classroom_operation_records', 'course_enrollment_request_history'),
            ('classroom_operation_records', 'classroom_proposal_members'),
            ('classroom_operation_records', 'classroom_attendance_disputes'),
            ('classroom_operation_records', 'classroom_gradebook_entries'),
            ('classroom_operation_records', 'lark_meeting_participants'),
            ('classroom_financial_records', 'classroom_tuition_payment_proofs'),
            ('classroom_financial_records', 'classroom_tuition_payments'),
            ('learner_progress_records', 'lesson_progress'),
            ('learner_progress_records', 'vocabulary_progress')
        ) AS mappings(domain_name, source_name)
    LOOP
        IF to_regclass('public.' || source_table) IS NULL THEN
            CONTINUE;
        END IF;

        FOR source_column IN
            SELECT attribute.attname AS column_name,
                   pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) AS sql_type
            FROM pg_catalog.pg_attribute attribute
            WHERE attribute.attrelid = to_regclass('public.' || source_table)
              AND attribute.attnum > 0
              AND NOT attribute.attisdropped
              AND attribute.attname <> 'id'
        LOOP
            target_column := CASE source_table || '.' || source_column.column_name
                WHEN 'teacher_course_feedback.learner_support_score' THEN 'feedback_learner_support_score'
                WHEN 'teacher_course_feedback.professionalism_score' THEN 'feedback_professionalism_score'
                WHEN 'teacher_performance_evaluations.learner_support_score' THEN 'evaluation_learner_support_score'
                WHEN 'teacher_performance_evaluations.professionalism_score' THEN 'evaluation_professionalism_score'
                WHEN 'teacher_google_meet_connections.status' THEN 'meet_connection_status'
                WHEN 'teacher_performance_evaluations.status' THEN 'evaluation_status'
                WHEN 'classroom_attendance_disputes.reason' THEN 'dispute_reason'
                WHEN 'classroom_attendance_disputes.status' THEN 'dispute_status'
                WHEN 'classroom_gradebook_entries.status' THEN 'gradebook_status'
                WHEN 'course_enrollment_request_history.reason' THEN 'transition_reason'
                WHEN 'lesson_progress.status' THEN 'lesson_progress_status'
                WHEN 'vocabulary_progress.status' THEN 'vocabulary_status'
                ELSE source_column.column_name
            END;
            EXECUTE format(
                'ALTER TABLE %I ADD COLUMN IF NOT EXISTS %I %s',
                domain_table,
                target_column,
                source_column.sql_type
            );
        END LOOP;
    END LOOP;

    FOREACH domain_table IN ARRAY ARRAY[
        'user_auxiliary_records',
        'assessment_component_records',
        'classroom_operation_records',
        'classroom_financial_records',
        'learner_progress_records'
    ]
    LOOP
        SELECT constraint_name INTO primary_key_name
        FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name = domain_table
          AND constraint_type = 'PRIMARY KEY'
        LIMIT 1;

        IF primary_key_name IS NOT NULL
           AND primary_key_name <> 'pk_' || domain_table THEN
            EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', domain_table, primary_key_name);
        END IF;
        EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET NOT NULL', domain_table);
        EXECUTE format('ALTER TABLE %I ALTER COLUMN record_type SET NOT NULL', domain_table);
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.table_constraints
            WHERE table_schema = 'public'
              AND table_name = domain_table
              AND constraint_name = 'pk_' || domain_table
              AND constraint_type = 'PRIMARY KEY'
        ) THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I PRIMARY KEY (id)', domain_table, 'pk_' || domain_table);
        END IF;
        primary_key_name := NULL;
    END LOOP;
END
$$^^^
