import { useCallback, useEffect, useState } from 'react';
import { Search } from 'lucide-react';
import adminApi from '../../api/adminApi';
import BrandedSelect from '../../components/ui/BrandedSelect';

const ACTIONS=['','ADMIN_USER_CREATED','ADMIN_USER_UPDATED','ADMIN_USER_ROLES_UPDATED','ADMIN_USER_STATUS_UPDATED','DISCUSSION_CONTENT_HIDDEN','DISCUSSION_REPORT_DISMISSED'];
export default function AdminAuditLogsPage(){
 const [logs,setLogs]=useState([]);const [keyword,setKeyword]=useState('');const [action,setAction]=useState('');const [page,setPage]=useState(0);const [totalPages,setTotalPages]=useState(0);const [error,setError]=useState('');
 const load=useCallback(async()=>{try{const data=await adminApi.getAuditLogs({keyword:keyword||undefined,action:action||undefined,page,size:20,sort:'createdAt,desc'});setLogs(data.content||[]);setTotalPages(data.totalPages||0);setError('');}catch(err){setError(err.response?.data?.message||'Không tải được nhật ký.');}},[keyword,action,page]);
 useEffect(()=>{const run=async()=>{await load();};run();},[load]);
 return <div><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#8a0018]">Quản trị</p><h1 className="mt-1 font-['Manrope'] text-2xl font-extrabold tracking-tight text-slate-900 sm:text-3xl">Nhật ký thao tác</h1><p className="mt-1.5 text-sm leading-relaxed text-slate-500">Theo dõi các thay đổi quan trọng trong hệ thống.</p></div><section className="mb-5 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label className="flex min-w-[280px] flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-[#fffdfc] px-3"><Search className="h-4 w-4 text-slate-400"/><input className="w-full bg-transparent py-2.5 outline-none" placeholder="Tìm đối tượng hoặc nội dung..." value={keyword} onChange={e=>{setKeyword(e.target.value);setPage(0);}}/></label><BrandedSelect buttonClassName="min-w-[220px] rounded-xl border-slate-200 py-2.5 shadow-none" value={action} onChange={(event) => { setAction(event.target.value); setPage(0); }} options={ACTIONS.map((item) => ({ value: item, label: item || 'Tất cả hành động' }))} /></section>{error?<p className="mb-4 rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>:null}<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-[1000px] w-full text-left"><thead className="bg-[#fff8f8] text-[11px] font-extrabold uppercase tracking-wider text-slate-500"><tr><th className="p-4">Thời gian</th><th className="p-4">Người thực hiện</th><th className="p-4">Hành động</th><th className="p-4">Đối tượng</th><th className="p-4">Chi tiết</th></tr></thead><tbody className="divide-y divide-slate-100">{logs.map(log=><tr className="hover:bg-[#fffafa]" key={log.id}><td className="whitespace-nowrap p-4 text-sm text-slate-600">{new Date(log.createdAt).toLocaleString('vi-VN')}</td><td className="p-4 text-sm font-semibold text-slate-800">{log.actorEmail}</td><td className="p-4"><span className="rounded-full bg-[#8a0018]/10 px-2.5 py-1 text-[10px] font-bold text-[#730014]">{log.action}</span></td><td className="p-4 text-sm text-slate-600">{log.targetType||'—'} {log.targetId?`#${log.targetId}`:''}</td><td className="max-w-md p-4 text-sm text-slate-600">{log.detail||'—'}</td></tr>)}</tbody></table>{!logs.length?<p className="p-10 text-center text-sm text-slate-500">Chưa có nhật ký phù hợp.</p>:null}</div><div className="mt-4 flex justify-end gap-3"><button className="rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:opacity-40" disabled={page<=0} onClick={()=>setPage(v=>v-1)} type="button">Trang trước</button><span className="px-2 py-2 text-sm font-semibold text-slate-600">{page+1}/{Math.max(totalPages,1)}</span><button className="rounded-lg border border-slate-200 px-3 py-2 text-sm disabled:opacity-40" disabled={page+1>=totalPages} onClick={()=>setPage(v=>v+1)} type="button">Trang sau</button></div></div>;
}
