import { useCallback, useEffect, useState } from 'react';
import { Edit3, Plus, Search, UserCog } from 'lucide-react';
import adminApi from '../../api/adminApi';

const ROLES = ['LEARNER','TEACHER','CONTENT_MANAGER','TRAINING_MANAGER','MANAGER','ADMIN'];
const emptyForm = { fullName:'', email:'', phoneNumber:'', password:'', roles:['LEARNER'] };

export default function AdminUsersPage() {
  const [users,setUsers]=useState([]); const [keyword,setKeyword]=useState(''); const [role,setRole]=useState(''); const [page,setPage]=useState(0); const [totalPages,setTotalPages]=useState(0); const [modal,setModal]=useState(null); const [form,setForm]=useState(emptyForm); const [error,setError]=useState('');
  const load=useCallback(async()=>{setError('');try{const data=await adminApi.getUsers({keyword:keyword||undefined,role:role||undefined,page,size:15,sort:'createdAt,desc'});setUsers(data.content||[]);setTotalPages(data.totalPages||0);}catch(err){setError(err.response?.data?.message||'Không tải được người dùng.');}},[keyword,role,page]);
  useEffect(()=>{const run=async()=>{await load();};run();},[load]);
  const openCreate=()=>{setModal('create');setForm(emptyForm);};
  const openEdit=(user)=>{setModal(user);setForm({fullName:user.fullName||'',email:user.email||'',phoneNumber:user.phoneNumber||'',password:'',roles:user.roles||[]});};
  const toggleRole=(value)=>setForm(current=>({...current,roles:current.roles.includes(value)?current.roles.filter(item=>item!==value):[...current.roles,value]}));
  const save=async(event)=>{event.preventDefault();setError('');try{if(modal==='create')await adminApi.createUser(form);else await adminApi.updateUser(modal.id,form);setModal(null);await load();}catch(err){setError(err.response?.data?.message||'Không lưu được người dùng.');}};
  const toggleStatus=async(user)=>{try{await adminApi.updateUserStatus(user.id,!user.enabled);await load();}catch(err){setError(err.response?.data?.message||'Không đổi được trạng thái.');}};
  return <div><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#8a0018]">Phân quyền</p><h1 className="mt-2 font-['Manrope'] text-3xl font-extrabold text-slate-900">Người dùng & vai trò</h1></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#730014] px-5 py-3 text-sm font-bold text-white" onClick={openCreate} type="button"><Plus className="h-4 w-4" />Tạo người dùng</button></div>
    <section className="mb-5 flex flex-wrap gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label className="flex min-w-[260px] flex-1 items-center gap-2 rounded-xl border border-slate-200 px-3"><Search className="h-4 w-4 text-slate-400"/><input className="w-full py-2.5 outline-none" onChange={e=>{setKeyword(e.target.value);setPage(0);}} placeholder="Tìm tên, email, số điện thoại" value={keyword}/></label><select className="rounded-xl border border-slate-200 px-4" onChange={e=>{setRole(e.target.value);setPage(0);}} value={role}><option value="">Tất cả vai trò</option>{ROLES.map(item=><option key={item}>{item}</option>)}</select></section>
    {error?<p className="mb-4 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>:null}
    <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-[1000px] w-full text-left"><thead className="bg-slate-100 text-xs uppercase text-slate-500"><tr><th className="p-4">Người dùng</th><th className="p-4">Vai trò</th><th className="p-4">Hồ sơ</th><th className="p-4">Trạng thái</th><th className="p-4 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-slate-100">{users.map(user=><tr key={user.id}><td className="p-4"><p className="font-bold text-slate-900">{user.fullName}</p><p className="text-xs text-slate-500">{user.email}{user.phoneNumber?` · ${user.phoneNumber}`:''}</p></td><td className="p-4"><div className="flex flex-wrap gap-1">{user.roles.map(item=><span className="rounded-full bg-[#8a0018]/10 px-2.5 py-1 text-[10px] font-bold text-[#730014]" key={item}>{item}</span>)}</div></td><td className="p-4 text-sm">{user.profileCompleted?'Đã hoàn thiện':'Chưa hoàn thiện'}</td><td className="p-4"><button className={`rounded-full px-3 py-1 text-xs font-bold ${user.enabled?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-600'}`} onClick={()=>toggleStatus(user)} type="button">{user.enabled?'Hoạt động':'Đã khóa'}</button></td><td className="p-4 text-right"><button className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-[#730014]" onClick={()=>openEdit(user)} type="button"><Edit3 className="h-4 w-4"/>Sửa / vai trò</button></td></tr>)}</tbody></table></div>
    <div className="mt-4 flex justify-end gap-2"><button disabled={page<=0} onClick={()=>setPage(v=>v-1)} type="button">Trang trước</button><span className="px-3 text-sm">{page+1}/{Math.max(1,totalPages)}</span><button disabled={page+1>=totalPages} onClick={()=>setPage(v=>v+1)} type="button">Trang sau</button></div>
    {modal?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form className="w-full max-w-2xl rounded-3xl bg-white p-6 shadow-2xl" onSubmit={save}><div className="mb-5 flex items-center gap-3"><UserCog className="text-[#730014]"/><h2 className="font-['Manrope'] text-2xl font-extrabold">{modal==='create'?'Tạo người dùng':'Chỉnh sửa người dùng'}</h2></div><div className="grid gap-4 sm:grid-cols-2"><input className="rounded-xl border p-3" required placeholder="Họ tên" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/><input className="rounded-xl border p-3" required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="rounded-xl border p-3" placeholder="Số điện thoại" value={form.phoneNumber} onChange={e=>setForm({...form,phoneNumber:e.target.value})}/><input className="rounded-xl border p-3" required={modal==='create'} type="password" placeholder={modal==='create'?'Mật khẩu':'Mật khẩu mới (tùy chọn)'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><p className="mb-2 mt-5 text-sm font-bold">Vai trò</p><div className="flex flex-wrap gap-2">{ROLES.map(item=><label className={`cursor-pointer rounded-full border px-3 py-2 text-xs font-bold ${form.roles.includes(item)?'border-[#730014] bg-[#fff1f2] text-[#730014]':'border-slate-200'}`} key={item}><input className="sr-only" type="checkbox" checked={form.roles.includes(item)} onChange={()=>toggleRole(item)}/>{item}</label>)}</div><div className="mt-6 flex justify-end gap-3"><button className="rounded-xl border px-5 py-2.5" onClick={()=>setModal(null)} type="button">Hủy</button><button className="rounded-xl bg-[#730014] px-5 py-2.5 font-bold text-white" disabled={!form.roles.length} type="submit">Lưu</button></div></form></div>:null}
  </div>;
}
