import { useEffect, useState } from 'react';
import { ArrowRight, ClipboardList, GraduationCap, Settings, ShieldCheck, Users, UserRoundCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import adminApi from '../../api/adminApi';

export default function AdminDashboardPage() {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { const load = async () => { try { setData(await adminApi.getDashboard()); } catch (err) { setError(err.response?.data?.message || 'Không tải được dashboard.'); } }; load(); }, []);
  const cards = [
    ['Tổng người dùng', data?.totalUsers, Users], ['Học viên', data?.learners, GraduationCap], ['Giáo viên', data?.teachers, UserRoundCheck], ['Nhân sự quản trị', data?.staffAndAdmins, ShieldCheck],
  ];
  return <div className="space-y-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#8a0018]">Quản trị</p><h1 className="mt-2 font-['Manrope'] text-3xl font-extrabold tracking-tight text-slate-900">Tổng quan hệ thống</h1><p className="mt-2 text-sm leading-relaxed text-slate-500">Theo dõi tài khoản, phân quyền và các thao tác quản trị trên EnglishLab.</p></div>{error ? <p className="rounded-2xl border border-[#ba1a1a]/20 bg-[#ffdad6] px-5 py-4 text-sm font-semibold text-[#93000a]">{error}</p> : null}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon]) => <section className="rounded-2xl border border-[#ead9db] bg-white p-5 shadow-sm" key={label}><div className="flex items-center justify-between"><p className="text-sm font-medium text-[#584140]">{label}</p><Icon className="h-5 w-5 text-[#8a0018]" /></div><p className="mt-3 font-['Manrope'] text-3xl font-extrabold text-[#4b0009]">{value ?? '—'}</p></section>)}</div><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="rounded-2xl border border-[#ead9db] bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-['Manrope'] text-xl font-extrabold text-slate-900">Thao tác nhanh</h2><p className="mt-1 text-sm text-slate-500">Các khu vực quản trị thường dùng.</p></div><ShieldCheck className="h-6 w-6 text-[#8a0018]" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><QuickLink to="/admin/users" title="Quản lý người dùng" description="Tạo, chỉnh sửa vai trò và trạng thái tài khoản." icon={Users}/><QuickLink to="/admin/settings" title="Cấu hình hệ thống" description="Kiểm tra thông tin cấu hình hiện có." icon={Settings}/></div></section><section className="rounded-2xl border border-[#ead9db] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#fff1f2] text-[#730014]"><ClipboardList className="h-5 w-5" /></span><div><h2 className="font-['Manrope'] font-extrabold text-slate-900">Nhật ký quản trị</h2><p className="text-sm text-slate-500">Theo dõi thay đổi quan trọng.</p></div></div><Link className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#730014] hover:text-[#4b0009]" to="/admin/audit-logs">Mở nhật ký thao tác <ArrowRight className="h-4 w-4" /></Link></section></div></div>;
}

function QuickLink({ to, title, description, icon: Icon }) { return <Link className="rounded-2xl border border-[#f0e3e4] bg-[#fcfbfb] p-4 transition hover:border-[#730014]/30 hover:bg-white" to={to}><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#fff1f2] text-[#730014]"><Icon className="h-4 w-4" /></span><p className="mt-3 text-sm font-extrabold text-slate-900">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></Link>; }
