import { useEffect, useState } from 'react';
import { CreditCard, Mail, Server } from 'lucide-react';
import adminApi from '../../api/adminApi';

export default function AdminSystemSettingsPage(){
 const [config,setConfig]=useState(null);const [error,setError]=useState('');
 useEffect(()=>{const load=async()=>{try{setConfig(await adminApi.getSystemConfig());}catch(err){setError(err.response?.data?.message||'Không tải được cấu hình.');}};load();},[]);
 const cards=config?[{title:'PayOS',icon:CreditCard,configured:config.payos.configured,rows:[['Client ID',config.payos.clientIdMasked],['API Key',config.payos.apiKeyMasked],['Checksum Key',config.payos.checksumKeyMasked]]},{title:'Mail',icon:Mail,configured:config.mail.configured,rows:[['Host',config.mail.host],['Port',config.mail.port],['Username',config.mail.usernameMasked]]},{title:'Ứng dụng',icon:Server,configured:true,rows:[['Active profile',config.app.activeProfile]]}]:[];
 return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8a0018]">Chỉ xem</p><h1 className="mt-2 font-['Manrope'] text-3xl font-extrabold tracking-tight text-slate-900">Cấu hình hệ thống</h1><p className="mt-2 text-sm text-slate-500">Thông tin nhạy cảm luôn được che trước khi hiển thị.</p></div>{error?<p className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error}</p>:null}<div className="grid gap-6 lg:grid-cols-3">{cards.map(({title,icon:Icon,configured,rows})=><section className="rounded-2xl border border-[#ead9db] bg-white p-6 shadow-sm" key={title}><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[#fff1f2] text-[#730014]"><Icon className="h-5 w-5"/></span><h2 className="font-['Manrope'] text-xl font-extrabold text-[#4b0009]">{title}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${configured?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{configured?'Đã cấu hình':'Thiếu cấu hình'}</span></div><dl className="space-y-4">{rows.map(([label,value])=><div className="rounded-xl border border-[#f0e3e4] bg-[#fcfbfb] p-3" key={label}><dt className="text-xs font-bold uppercase tracking-wide text-[#8b706e]">{label}</dt><dd className="mt-1 break-all font-mono text-sm text-slate-700">{value}</dd></div>)}</dl></section>)}</div></div>;
}
